### ISSUE TITLE
Add .contains() or .includes() to Array

### ISSUE THREAD

**Issue by dlee** [andrewplummer/Sugar#175]
Just shorthand for doing:

``` javascript
array.indexOf(e) != -1
```

**Comment by lolmaus** [comment]
I was surprised to discover that this is missing!

I want to be able to do this

```js
arr.contains('foo')
```

instead of this

```js
arr.indexOf('foo') > -1
```

and of course instead of this

```js
arr.some( function(e) { return e === 'foo'; })
```

Please reopen. There is no excuse not to have `.contains`.

**Comment by alFReD-NSH** [comment]
As they said above, you can do `arr.some('foo')` or `arr.any('foo')`...

**Comment by lolmaus** [comment]
Uhm, it works, but:

1. It's not documented.
2. It's not readable. When a dev not familiar with Sugar encounters `arr.some('foo')`, he will be puzzled. `arr.contains('foo')` is self-explanatory.

**Comment by alFReD-NSH** [comment]
Yeah, it's not readable, I do agree with that.

**Comment by zloirock** [comment]
@lolmaus Андрюша, зачем плодить 100500 нестандартных методов / ломать стандартные, если есть стандартизованный `.includes`, а где его взять - думаю и так ясно :)

**Comment by andrewplummer** [comment]
These are some interesting points and I understand where they're coming from. To the first point, it actually is documented but you have to click through to the "enhanced array methods" section, which people probably don't do. So I think I should clean up the documentation here and (even better) add inline examples to make it more obvious.

To the second point, I would say that being not readable was the problem that `arr.any('foo')` attempts to address, but I can't deny that `arr.contains('foo')` is even clearer.

What if we aliased `contains` instead and deprecated `any`?

**Comment by lolmaus** [comment]
@zloirock, Deniska, [Array.prototype.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) is part of ES7.

I do not know where to get it in browser or Node. Probably there is some polyfill you weren't willing to share a link to. I believe Sugar should provide a polyfilled `.includes`.

~~Carthage must be destroyed.~~ Please reopen.

**Comment by andrewplummer** [comment]
Oh crap that's right... I knew I was missing something... `Array.prototype.includes` is indeed part of the next harmony proposal so this will not work as an alias. Polyfill may be an option but the problem is that if the spec changes, it may become an issue.

**Comment by lolmaus** [comment]
@andrewplummer, well, you've got a pompous manifest taking care of that. ;)

**Comment by zloirock** [comment]
@lolmaus именно :) Где взять? IIRC, пользуешься `babel`, с большой долей вероятности и его полифилом, а это `core-js`, он там искаропки. А нет - никто не мешает подключить метод как одиночную фичу. Хотя да, в шуге тоже было бы неплохо стандартизованный функционал иметь, так как до сих пор кое где использую.

**Comment by andrewplummer** [comment]
@lolmaus I've got a what now? :)

**Comment by lolmaus** [comment]
@zloirock, by writing in a local language you're being impolite.

@andrewplummer, this:

> Part of being compliant with standards also means adapting to changes in spec. It is Sugar's reponsibility to stay on top of the standards and align itself early to new spec to smooth the transition later.
> ...

**Comment by zloirock** [comment]
@lolmaus да пофик, обращаюсь то не ко всем, а то от этого вашего "глобального" крыша съезжает уже :D

**Comment by andrewplummer** [comment]
@lolmaus Ah yes, that. Well that's fine for people who read it, but also have to think about avoiding problems up front. That said, this spec seems to have gained some maturity, and I would definitely be open to the idea of a polyfill.
