### ISSUE TITLE
[Suggestion]  nl2br() and tag()

### ISSUE THREAD

**Issue by metaseit** [andrewplummer/Sugar#275]
How about a function to turn line-break into html BR? It would be useful to display string (usually ajax response) to html with line break. Using paragraphs() and join() is ok, but nl2br() is more straight to the point:
$("#flash").html( json.message.paragraphs().join("<br>") );
- vs -
  $("#flash").html( json.message.nl2br() );

And I am looking for a function to wrap text by html tag like PRE, P, etc. There is small(), sub(), sup() native functions. It would be good to have more. jQuery wrap() works, but is not elegant enough:
$("#flash").html( $(json.message).wrap("<pre></pre>") );
- vs -
  $("#flash").html( json.message.tag("pre") );
- or -
  $("#flash").html( json.message.pre() );

**Comment by andrewplummer** [comment]
Plugins are now supported in 2.0.0. I'm running out of ways to apologize for taking so long on these issues, but [here](https://github.com/andrewplummer/Sugar/issues/296) is another one.
