### ISSUE TITLE
Method to get pixel values from image data array

### ISSUE THREAD

**Issue by billymoon** [andrewplummer/Sugar#292]
Function to get the pixels at a given point of a pixel array. I can't think of more general terminology, but my use case is this...

I have an array of pixels, rather like a buffer in node.js after loading an image file to a pixel array, or loading data from a canvas element. I want to refer to each pixel by it's x, y co-ordinates. If the width of my image is 65, and I want pixel at point 10,10 - I want to say myDataArray(10,10,65) and be returned an array of the 4 elements making up my pixel (as defined by stride - default value of 4).

```
Array.extend({
  pixel: function(x, y, width, stride) {
    if (stride == null) {
      stride = 4;
    }
    return this.slice(x * stride + width * y * stride, x * stride + width * y * stride + 4);
  }
});
```

**Comment by andrewplummer** [comment]
As the person who's had the most suggestions for plugins, you will be at least getting multiple apologies for how long I've taken. Just to be thorough, [here](https://github.com/andrewplummer/sugar-plugin-boilerplate) again is the repo for creating a Sugar plugin. Here's praying that you haven't given up all hope.
