### ISSUE TITLE
Add Object.invert()

### ISSUE THREAD

**Issue by kevincox** [andrewplummer/Sugar#298]
It replaces a objects keys with it's values.

**Comment by andrewplummer** [comment]
So, despite the ridiculous amount of time that's passed on this bug, this method is finally getting implemented! woohoo!  Hope you're still around...................

**Comment by kevincox** [comment]
I am still watching 👀

**Comment by andrewplummer** [comment]
Incredible... Well all I can say is sorry about the delay. Hopefully the updates will be worth it....

**Comment by kevincox** [comment]
No worries, I can see that you have been doing a lot of infrastructure work which is important before adding more functionality.

**Comment by andrewplummer** [comment]
As the only one left of these ancient issues who seems to still be checking, I can now finally say that this has gone out! Thank you for your patience!
