### ISSUE TITLE
Send feedback to es-discuss

### ISSUE THREAD

**Issue by DavidBruant** [andrewplummer/Sugar#352]
From #350 :

> it's not like ECMAScript is churning out new specs left and right. find and findIndex may be the last collision we see forever.

Anytime we feel that "this collision may be the last", we find yet another library and yet another collision :-)

[es-discuss](https://mail.mozilla.org/listinfo/es-discuss) is a mailing list where people talk about the future of ECMAScript, including the ECMA TC39 group who's making the standard. I know that they're pretty eager to get feedback from developers who would have ideas on how to improve the language.

It'd be interesting if at some point the Sugar project came to es-discuss to share what ideas they've implemented and what they have seen to be the most successful and if relevant, suggest the addition of new built-ins to the language.

This doesn't need to happen now, but I'm filing the issue as a reminder.

**Comment by andrewplummer** [comment]
ok this took ages but I was on a bit of a hiatus until a while back and this somehow fell into the bottom of a very large todo list... I just subscribed to the mailing list, and will make sure to new points on my radar and jump into discussions as needed.

thanks!
