### ISSUE TITLE
reduce should iterate over keys and values

### ISSUE THREAD

**Issue by D1plo1d** [andrewplummer/Sugar#357]
The reduce method appears to be broken for Objects in that it does not iterate over the keys of the object.

When I run the following in cs:

`Object.reduce { x: 10, y: 20, z: 5 }, (-> console.log arguments), ''`

I get the following output:

```
{ '0': '', '1': 10, '2': 0, '3': [ 10, 20, 5 ] }
{ '0': undefined, '1': 20, '2': 1, '3': [ 10, 20, 5 ] }
{ '0': undefined, '1': 5, '2': 2, '3': [ 10, 20, 5 ] }
```

What I was expecting was:

```
{ '0': '', '1': 'x', '2': 10 }
{ '0': undefined, '1': 'y', '2': 20 }
{ '0': undefined, '1': 'z', '2': 5 }
```

**Comment by andrewplummer** [comment]
Reopening this as a reminder before release
