### ISSUE TITLE
More sophisticated date ranges.

### ISSUE THREAD

**Issue by andrewplummer** [andrewplummer/Sugar#367]
Would ideally like to be able to say:

```
Date.range('tomorrow at 3pm for 30 minutes')
```

etc.

**Comment by marleyblakedog** [comment]
Can this be extended to allow, e.g., `Date.range('tomorrow from 3pm to 5pm')`? Currently, if you try something like 'tomorrow at 3pm until 5pm', you get [tomorrow 3:00pm, today 5:00pm].

It seems to me that Date.range should be assuming that the end date is >= the start date, though that might be seen as a breaking change.

**Comment by andrewplummer** [comment]
That's an interesting Idea. I think it should be possible... the "from" token could indicate that the 2nd portion of the date would be a `future` event. As mentioned in other threads, full on date range parsing starts to impede on NLP territory and gets complex quickly, but I would like to have some basic support like this.

**Comment by andrewplummer** [comment]
ok, after taking forever this one will be going out soon.

I've also ensure that the format `tomorrow from 3pm to 5pm` works as you suggested. This is thanks to `Date#get` which is a new method that functions like `Date.create` but uses the contextual date as an indicator for ambiguous formats. That means that if you call it with a format like `5pm` on a date, it will assume that date (instead of the current date). The `from..to` format for ranges simply constructs the first date then uses that as the context date for the 2nd one. This allows a lot more intelligence in range construction.

anyway, look for it soon!

**Comment by andrewplummer** [comment]
This is out!
