### ISSUE TITLE
Symbol to proc

### ISSUE THREAD

**Issue by esad** [andrewplummer/Sugar#371]
See https://gist.github.com/brianewing/2300335

This is useful for many things, for example one could write:

```
array.any('expired'.proc)
```

instead of

```
array.any(function(el) { return el.expired(); })
```

Do you think there's place for this in Sugar?

**Comment by andrewplummer** [comment]
If anyone is still around to hear this, 2.0.0 has been released, and supports the ability to define plugins. I've created a [repo](https://github.com/andrewplummer/sugar-plugin-boilerplate) with boilerplate to get plugins started, so please refer to it! Thank you and I'm very sorry for the delay here.
