### ISSUE TITLE
Custom Build Script Not Included In Bower Package

### ISSUE THREAD

**Issue by aedenj** [andrewplummer/Sugar#372]
I'm new to Bower so excuse me if my question is misplaced. I think it would be nice to include the necessary scripts to do a custom build within the bower package. What say y'all?

**Comment by andrewplummer** [comment]
Hi, so really sorry for the long delays. v2.0.0 is going to be released finally and I've had a long look at how the package building will work and re-worked the bower.json file for Sugar.

That said, I still don't know what you mean by "custom build within the bower package". If you want the different packages to be separated (`array`, `string`, etc), I'm having a look at that right now for the npm package, and based on that decision this might happen.

If you mean creating custom builds, then this will be possible in the npm package using gulp. However bower is a different ecosystem, so I'm not quite sure how that would work.

Anyway I'm going to close this one out for now, but feel free to re-open if you like.
