### ISSUE TITLE
Problem with Object.clone with accessors

### ISSUE THREAD

**Issue by chtulhu6662000** [andrewplummer/Sugar#396]
It seems like Object.clone doesn't re-create accessors when cloning, which leads to a break in behavior.

For instance:

```
    var template = {
        data: {label: 'new node'},

        get label() {return this.data.label;},
        set label(value) {  this.data.label = value;}
    };

    var test = Object.clone(template);
    test.label = 'not working';
    console.log(test.data.label); // Should be 'not working', but instead is 'new node'
```

**Comment by andrewplummer** [comment]
Ok this has gone out with 2.0.0. Essentially you will pass a flag to merge to tell it to use property descriptors when needed. Syntax is:

```javascript
Sugar.Object.merge(target, source, {
   descriptor: true
});
```

This may also use the `hidden` field if the property is non-enumerable. See [here](https://sugarjs.com/docs/#/Object/merge) for more information. Thanks!
