### ISSUE TITLE
Add Number#sign

### ISSUE THREAD

**Issue by Zegnat** [andrewplummer/Sugar#406]
Not sure whether to make a pull out of this, so putting it up here first. Should Sugar include a [sign function](http://en.wikipedia.org/wiki/Sign_function)?

It is more work to effectively figure out if something is a negative number or not (what a number’s sign is) than you might think. Thankfully [several StackOverflow contributors have done most of the work](http://stackoverflow.com/questions/7624920/number-sign-in-javascript):

``` js
function sign(x) {
    return typeof x === 'number' ? x ? x < 0 ? -1 : 1 : x === x ? 0 : NaN : NaN;
}
```

This does not consider [signed zeroes](http://en.wikipedia.org/wiki/Signed_zero), while JavaScript [definitely has them](http://www.wirfs-brock.com/allen/posts/128). A slight change to the above function to return `x` instead of `0` seems to fix this and makes it compatible with [ES6’s Math.sign](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-math.sign).

I am currently using the following in a little sugar extension file that I personally use, but it might be an idea to include it in the core?

``` js
Number.extend({
    'sign': function() {
        return typeof this === 'number' ? this ? this < 0 ? -1 : 1 : this === this ? this : NaN : NaN;
    }
});

/*
    (Infinity).sign() =>  1
    (50).sign() =>  1
    (0).sign() =>  0
    (-0).sign() =>  -0
    (-50).sign() =>  -1
    (-Infinity).sign() =>  -1
    (NaN).sign() =>  NaN
*/
```

Possibly `isPositive` and `isNegative` could be added also, as companions of `isOdd` and `isEven`. The question then is what they should report on signed zeroes.

**Comment by andrewplummer** [comment]
Well, who knows if you're even still alive after I've finally gotten to this one, but let it be known that 2.0.0 has been released for a while, and supports the ability to define plugins. I've created a [repo](https://github.com/andrewplummer/sugar-plugin-boilerplate) with boilerplate to get plugins started, so please refer to it! Thank you and I'm very sorry for the delay here.

**Comment by Zegnat** [comment]
Still alive. Not sure if an entire repo for this little thing makes sense though. Leaving it here in case someone needs it and finds this issue:

```javascript
(function (Sugar) {
  var signum = function (x) {
    return x ? x < 0 ? -1 : 1 : x === x ? x : NaN
  }
  Sugar.Number.defineInstance({
    'sign': signum,
    'isPositive': function (x, zero) {
      if (zero === true) x = 1 / x
      return signum(x) > 0
    },
    'isNegative': function (x, zero) {
      if (zero === true) x = 1 / x
      return signum(x) < 0
    }
  })
})(Sugar)
```

`.sign` works exactly how I described it before. `.isPositive` and `.isNegative` will give back boolean values, pretty self explanatory. They also offer an extra parameter that, if set to true, will test zeroes for their sign. This means `(0).isPositive(true)` and `(-0).isNegative(true)` will return true. Normally a zero will return false for both.

**Comment by andrewplummer** [comment]
> Not sure if an entire repo for this little thing makes sense though.

It doesn't *necessarily* need a repo, just it's own npm package, but why not? There's no premium on repo space :)

Anyway it is non-trivial work, so I'll leave it up to you. Thanks for responding!
