### ISSUE TITLE
Feature Request & Early Implementation: lib/date.js parsing needs less strict option

### ISSUE THREAD

**Issue by ghost** [andrewplummer/Sugar#415]
Date parser is really good and really annoying, too. It is too strict compared to moment.js (which has a strict feature as an option). I had to manually modify some code in lib/date.js, to make it kinder. Can we have an option?

Strict default setup:

``` js
 // General helpers

  function addDateInputFormat(locale, format, match, variant) {
    locale.compiledFormats.unshift({
      variant: variant,
      locale: locale,
      reg: regexp('^' + format + '$', 'i'),
      to: match
    });
  }
```

Not so strict:

``` js
 // General helpers

  function addDateInputFormat(locale, format, match, variant) {
    locale.compiledFormats.unshift({
      variant: variant,
      locale: locale,
      reg: regexp(format, 'i'),
      to: match
    });
  }
```

**Comment by andrewplummer** [comment]
Hey thanks, going to actually keep this open as a reminder until release.

**Comment by andrewplummer** [comment]
Ok closing this as 2.0.0 has been out for a while now. I've essentially exposed a number of previously minified properties, so looking under the hood of the locale objects should be easier now. Thanks!
