### ISSUE TITLE
Hyphens and hankaku()

### ISSUE THREAD

**Issue by DarrenCook** [andrewplummer/Sugar#418]
I wanted automatic conversion of Japanese postcodes, from zenkaku to hankaku. This kind of works:
  value = value.hankaku('all');

It converts １２３４５６７ to 1234567. But with １２３ー４５６７ it does not handle the hyphen the way I expect. It turns "ー" into "ｰ", rather than "-" (Yeah, I know that is a bit hard to see, but I expected an ascii hyphen, and instead I get a hankaku katakana hyphen.)

I'm not sure that is something that can be fixed; perhaps we just need to clarify the documentation (which I can volunteer to do). But before touching anything I wanted to get other people's thoughts.

**Comment by andrewplummer** [comment]
Ok this is out now, so closing!
