### ISSUE TITLE
Make a docset for Dash

### ISSUE THREAD

**Issue by zharikovpro** [andrewplummer/Sugar#421]
Here's a great offline API browser: http://kapeli.com/dash
It would be really great to always have SugarJS API in Dash.

**Comment by andrewplummer** [comment]
Thanks for this issue (about a billion years later). Work on Sugar was stagnating a bit, but v2.0.0 is soon to be released. There's a lot of changes that have to be made to the site's docs, but I've made a note that after everything is released to go back and look at Dash. It looks like I can easily [generate the docset from the HTML source](https://github.com/technosophos/dashing#readme) so I'll probably have a look at doing it that way.

Going to close this issue out for now. Thanks!
