### ISSUE TITLE
isBetween() is greater and lessthan not greaterOrEqualTo and lessThanOrEqualTo 

### ISSUE THREAD

**Issue by startswithaj** [andrewplummer/Sugar#425]
```
return (lo - margin < t) && (hi + margin > t);
```

12:00am to me is between 12:00am and 23:59:59

If you are trying to find dates that fall on a particular day it makes sense to me that the following code should return true.

```
 Date.create().beginningOfDay().isBetween(Date.create().beginningOfDay(), Date.create().endOfDay()) //returns false
```

Is there a more logical solution to having the above return true than passing in an allowance of 1ms?

```
 Date.create().beginningOfDay().isBetween(Date.create().beginningOfDay(), Date.create().endOfDay(), 1) //returns true
```

**Comment by andrewplummer** [comment]
Well, that only took a year and a half! Thank you for this and will go out soon!

**Comment by andrewplummer** [comment]
Ok, this has been out for a while now so closing!
