### ISSUE TITLE
Object.watch documentation incomplete

### ISSUE THREAD

**Issue by btesser** [andrewplummer/Sugar#429]
Object watch documentation doesn't specify that return value of passed method will be assigned to the object

**Comment by andrewplummer** [comment]
Note that `Object.watch` will be removed in 2.0.0 but available as a plugin. Various reasons for this. I can go into it if you're interested. Anyway will leave this ticket open as a reminder to make the docs good when I do the plugin.

**Comment by andrewplummer** [comment]
Ok I'm going to close this now. `watch` is removed as of 2.0.0, and considering the time that's passed I'm going to leave it alone, as it's not reliable or recommended. If you still have a need for this, then I can *possibly* consider releasing the old code as a plugin, but I first recommend reading up on `Object.observe` and why it was deprecated, as well as the new recommendations moving forward to see if it really will bring any value. Thanks!
