### ISSUE TITLE
Object.watch runs method when value unchanged

### ISSUE THREAD

**Issue by btesser** [andrewplummer/Sugar#430]
Object.watch will call method even if the object value is set to the already set value.

For example:
```
z = {a: 'test'};
Object.watch(z, 'a', function(){return 'test'});
z.a = 'test';
```
(method runs)

**Comment by andrewplummer** [comment]
Sorry this has taken so long... Going to close this one out for now. Object.watch is removed in v2.0.0 of Sugar as it is a notoriously bad solution... for one it's non-performant (see many other threads about Object.observe), and non-reliable (impossible to do in < IE9). 2.0.0 will support plugins so it will be moved into it's own plugin. When that happens I'll have another look at your idea.

Also note that right now watch is significantly different from [Firefox's](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch) implementation, so there might be value in bringing those together.

**Comment by andrewplummer** [comment]
Just a last note on this, I'm opting not to do the plugin for this either, for the above reasons.
