### ISSUE TITLE
Bug Parsing 'ten minutes ago' in v1.4.1

### ISSUE THREAD

**Issue by v-ramachandran** [andrewplummer/Sugar#431]
I use Sugar's dates parsing for creating dates from user input. I believe there a seems to be a bug when parsing "ten minutes ago." I receive the same output as current time when doing so. Specifically:

> > > Date.create()
> > > Date {Wed May 21 2014 18:23:28 GMT-0700 (PDT)}
> > > Date.create("ten minutes ago")
> > > Date {Wed May 21 2014 18:23:32 GMT-0700 (PDT)}

In addition, it seems like beyond "ten," the library does not recognize spelled-out numbers. Is this expected behavior?

And, I just want to mention that you've done great work with this library!

**Comment by andrewplummer** [comment]
Released!
