### ISSUE TITLE
include inflection in the main NPM package?

### ISSUE THREAD

**Issue by palominoz** [andrewplummer/Sugar#436]
I think people would expect all documented methods available by default within node environments, in my opinion there is no real need for custom builds there. 

Beside that i still cannot use `"test, string".parameterize()` since parameterize is `undefined`, even if the function exists in `sugar-full.development.js:7788`. How can I fix this?

Things I did under node 0.10.26
```
npm install sugar
[..somewhere..]
require('sugar')
string.parameterize()
# => throws undefined
[...]
```

**Comment by andrewplummer** [comment]
Hey guys... this one has taken a ridiculous amount of time to get to, but it's finally happening, and as of v2.0.0, Sugar will be split out into separate packages. There are a lot of details to flesh out however, so I created a new ticket for this one:

https://github.com/andrewplummer/Sugar/issues/522

Please have a look and comment. Closing this one in the meantime.
