### ISSUE TITLE
Array.median() missing

### ISSUE THREAD

**Issue by dev101** [andrewplummer/Sugar#439]
It would be be great to have **Array.median()** to calculate median value. Often _average()_ is not enough for a statistical analysis.
See https://gist.github.com/caseyjustus/1166258 for implementation.

**Comment by andrewplummer** [comment]
Looks like I severely underestimated the amount of time this would take. However it's in now!
As with `average`, you will be able to map deep data like so:

```
users.median('age')
```

also as of 2.0.0 you can do a deep property map as well:

```
users.median('profile.age');
```

**Comment by andrewplummer** [comment]
Closing this now as it's been released!
