### ISSUE TITLE
fill treat null as undefined

### ISSUE THREAD

**Issue by Alexsey** [andrewplummer/Sugar#446]
```
var filledLog = console.log.fill(null, undefined, '3')
filledLog('1', '2')
```

 logs
<code>'1 2 3'</code>

should log
<code>'null 1 3 2'</code>

if <code>null</code> must be treat as <code>undefined</code> - change, please, <code>fill</code> documentation

But i think it should not (for example in NodeJS <code>null</code> is typical valid first argument for callback which has been execute with on error)

**Comment by tschettler** [comment]
@Alexsey I would also prefer to allow fill to work with null parameters.

**Comment by andrewplummer** [comment]
Hi, I'm really sorry. This issue hasn't been responded to in over a year, which is just ridiculous. It fell into the cracks of a backlog of open issues and I'm just now getting to it. Will try to follow up from now on!

Now to the issue:

I totally agree.

That's it.

It's very clear to me treating `null` as `undefined` was an oversight, and it needs to be changed. Fortunately now is the time to do this as there are a lot of rewrite going on now.

**Comment by Alexsey** [comment]
thanks for feedback, glad that work on Sugar is continued

**Comment by andrewplummer** [comment]
Note that `fill` is going to be renamed to `partial` in 2.0.0 in order to bring the name in line with other common libs and avoid confusion. I've brought in tests to ensure compatibility. `null` will be treated as a real value as this ticket describes.

**Comment by andrewplummer** [comment]
This has been released, so closing this ticket now.
