### ISSUE TITLE
Unexpected Date range

### ISSUE THREAD

**Issue by ccorcos** [andrewplummer/Sugar#452]
`Date.range('tomorrow 5pm', '8pm')`

Is there any way to coerce future to be after the start date?

**Comment by andrewplummer** [comment]
Sorry again for the insane delay responding to this. 

Right now you can do this:
```
Date.range('tomorrow at 5pm', Date.future('8pm'));
```
This will change in 2.0.0 to this:
```
Date.range('tomorrow at 5pm', Date.create('8pm', { future: true }));
```

Additionally you will also be able to do this:
```
var d = Date.create('tomorrow at 5pm');
Date.range(d, d.get('8pm', { future: true });
```

`get` is a new method that is essentially `create` but uses the current instance as a context for creating the new date, exactly for situations like this. As of right now there is no way to do this but of course if you know the date ahead of time as in the example you could do this:
```
Date.range('tomorrow at 5pm', 'tomorrow at 8pm');
```

2.0.0 will be out soon (still not sure... won't be tomorrow or anything but hopefully pretty soon)

thanks for your patience!
