### ISSUE TITLE
Some ideas for date parsing tweaks

### ISSUE THREAD

**Issue by blabus** [andrewplummer/Sugar#455]
Unbelievable work so far with Sugar, particularly its date parsing features. I've integrated it into a project and it's been working great so far, but I had a few notes about certain natural language dates and how the parsing of them might be improved:
- (Assuming it's currently Monday the 11th, for example), "A week from Sunday" returns a week from the previous Sunday (the 10th), where as I think in most instances the user probably means a week from the coming Sunday?
- "Week from [date]" is not parsed, "A week from [date]" is. Would be nice to not require the leading "A".
- Support for parsing "noon" and "midnight".
- "First of the month" is not parsed, "The first day of the month" is. The former is likely the more common wording used by most.
- "Tomorrow at 4" is not parsed, "Tomorrow at 4pm" is. This one is tricky as it's not always clear if an isolated digit is meant to be the hour, but again, just some phrases you might expect to hear someone audibly speak.

Anyway, stellar work so far on all of this, these points are really just nice-to-haves, but I figured I'd throw them out there. Keep up the great work!

**Comment by andrewplummer** [comment]
Hi, really sorry to leave you hanging on this issue... I appreciate the contribution! To answer your points:

- This can now be done using `future`: `Date.future.create('a week from Sunday')`. Also `past` exists. When using just `Date.create` the assumption is that a weekday means "of the current week". We can argue about which one is more likely but the fact is that it's ambiguous and which is more likely is entirely dependent on context, which is why this method was developed. Also note that v2.0.0 will change this to be an options object instead: `Date.create('a week from Sunday', { future: true });`

- I had initially tried to avoid non-natural phrasing such as "week from ... " without "a", but I understand your point about being more lenient. Will have a look.

- I think this actually was supported at one point but removed because it seemed unnecessary, but I'm willing to add it back if you think it would be useful

- Same as the second point

- This one might be tricky. As you say having digits without tokens to give hints to their meaning may have unintended consequences. However if I can do this easily without breaking everything else, I'll try.

Thanks!

**Comment by andrewplummer** [comment]
Ok I've addressed some of your issues:

- `week from Monday` etc. is now supported
- `noon` and `midnight` is now supported (#453)
- `first of the month` is now supported
- `tomorrow at 4` will *not* be supported, not because it's an isolated digit, but because am/pm is ambiguous (see #513)

**Comment by tuscanknox** [comment]
A few more suggestions:

1. Support for "first, second, third, etc..." (distinct from "1st, 2nd, 3rd...") would be SUPER awesome. 
2. Support for "in" as well as "of" for the format "the third monday in june."
3. Alias "weekend" to "saturday" so things like "next weekend" work out
4. Support for "last" as in "the last monday in june"  (probably impossible)

regardless, sugar is the best natural language date parser available in javascript.  it's fantastic.

**Comment by andrewplummer** [comment]
Done. All great ideas and good timing as it dovetailed with some other new implementations.

**Comment by vendethiel** [comment]
sorry, dovetailed?

**Comment by andrewplummer** [comment]
Ya, I just meant that I had done a lot of work on the internals here that made a couple of these possible...

**Comment by Earl-Brown** [comment]
First, a compliment - I LOVE sugar!

Now a suggestion: "in half an hour" doesn't parse (=> "invalid date").  I realize this has MANY variations (even just for half an hour ... but what kind of granularity should be included?  "In one thirtieth of an hour"? ... I'll leave that decision to you, Andrew! :)

Other versions I've tried: "in 1/2 hour", "in one half hour"

It seems that the division format would be useful for arbitrary values ... and that implies "in 0.5 hours" should work, too...which would be the midpoint from the divisional versions.  1/2 -> 0.5 -> 30 [units].

Thanks, again!

**Comment by andrewplummer** [comment]
Hi... I've added the token "half" as a special token that can be added to any locale, but I think I'm going to draw the line there. Anything beyond that for fractions "a third", "a quarter", is fairly non-colloquial and has a lot of diminishing returns for the added complexity. The same goes for fractional notation... in addition to added parsing time, fractional notation needs to know not only about the current unit but the one above it, which is non-trivial and simply not worth it IMO. If a number of locales report about fractional notation being more common than English I'll re-examine this.

**Comment by andrewplummer** [comment]
Also note that "half" will work with units set numerically ("millisecond" through "day") and also with "year" as a special case (reverts to 6 months). "month" and "week" will NOT work with "half" as they aren't meaningful.

**Comment by Earl-Brown** [comment]
Works for me!  Thanks

**Comment by krittick** [comment]
Not sure if this should get its own issue but:

Can "a.m." and "p.m." be added as valid formats for "am/pm"? Chrome's SpeechRecognition API (as an example) detects the spoken version as "a.m." and "p.m." and these aren't considered valid by sugar:

```javascript
Date.create('4 p.m.');
 // Invalid Date
Date.create('4 pm');
// Tue May 10 2016 16:00:00 GMT-0700 (Pacific Daylight Time)
```

It's fairly trivial to work around with a quick regexp, but it would be ideal if sugar handled it natively to avoid needing to add the workaround each time I need to recognize speech or other natural language inputs.

**Comment by andrewplummer** [comment]
OK! Will be in the next version!

**Comment by vendethiel** [comment]
"Next version" :P

**Comment by andrewplummer** [comment]
These have gone out, so closing this now.
