### ISSUE TITLE
sugarjs inside angularjs scopes

### ISSUE THREAD

**Issue by sirpy** [andrewplummer/Sugar#456]
two quesitons
1. how can I use sugar js as a standalone function such as underscore. (ie Sugar([1,2,3]).find...)
2. angularjs uses scopes, so when importing sugarjs only the main windows is extended with sugarjs but angularjs scopes are not. when using angular expressions {{}} sugarjs extended objects are not available

**Comment by andrewplummer** [comment]
Going to close this one out now as it seems to be answered.
Note that right now v2.0.0 is under development which will allow Underscore-like behavior in accessing through a global, which answers your first question.
