### ISSUE TITLE
Error in .compact documentation

### ISSUE THREAD

**Issue by Alexsey** [andrewplummer/Sugar#460]
It says "Removes all instances of undefined, null, and NaN from the array", but
```
console.log([null, [1, null, 2], [null, 1, [1, null, 2]], [null]].compact())
```
Outputs
```
[ [ 1, 2 ], [ 1, [ 1, 2 ] ], [] ]
```
which means it draw not array, but array and all sub-arrays recursively

IMHO Ideal if we could control the deepness of clean... without it method looks incomplete 

For now it should be at list mentioned in docs

Thanks

**Comment by andrewplummer** [comment]
Absolutely agree. Mentioned this in #462 as well, so for now will close this in favor of that one.

**Comment by andrewplummer** [comment]
Also sorry to take forever to respond.
