### ISSUE TITLE
.compact(true) is broken

### ISSUE THREAD

**Issue by Alexsey** [andrewplummer/Sugar#462]
```
console.log([null, 1, '', [1, '', null]].compact(true))
```

Outputs

```
[1, [1, '']]
```

Which means that <code>null</code>s has been removed deeply, but <code>''</code> only on first level of array

Bug is in different behavior for different entities

Correct behavior according to documentation in not to remove any values in nested arrays

**Comment by andrewplummer** [comment]
First of all very sorry to take ages on this. This is indeed a bug but furthermore I think it's very unexpected to deeply compact by default without some kind of warning or flag. Now is the time to change this... What do you think?

**Comment by Zegnat** [comment]
I think it makes sense to make it follow the documentation and only work on the array the method is called on:

```javascript
[null, 'hi', [null, 'bye']].compact() === ['hi', [null, 'bye']]
```

I am not sure what the use-case would be for making it work on nested elements.

**Comment by andrewplummer** [comment]
Totally agree. If there is a use-case for nested then it's perfectly fine for it to be done explicitly:

```
arr.compact();
arr.forEach(function(inner) {
   inner.compact();
});
```

**Comment by Zegnat** [comment]
Additionally I would propose adding an example like the code from my previous comment to the docs, so people actually understand how nested arrays work?

**Comment by andrewplummer** [comment]
Definitely will do!

**Comment by Alexsey** [comment]
Well, there is a different between recursively and one level applying, so just <code>.forEach</code> is not enough, but what your saying is true - flat case is more common and what is more impotent it is more expected for people who work (before) with <code>lodash/underscore</code> because their behavior is flat and even have no deep flag

**Comment by andrewplummer** [comment]
> Well, there is a different between recursively and one level applying
Totally agree. Actually in that example I was mostly just trying to say that it's very hard to imagine a use-case where you have an array that needs to be compacted that's an *unknown* number of levels deep! If such a strange situation did occur it would be possible to write your own recursive function to do it and I would argue that that would be the correct action given the obscure use case.

In the end `compact` was a method added very early on when I was being over-zealous and not giving enough attention to the fact that often handling *mininal* use cases gives more flexibility and utility in the end.

Anyway this will change!

**Comment by vendethiel** [comment]
I might be a bit late on this one, but don't several methods have a `deep` boolean flag?

**Comment by andrewplummer** [comment]
No, only `flatten` has a parameter `level` to indicate what dimension to flatten to.
