### ISSUE TITLE
String::has option case insensitivity

### ISSUE THREAD

**Issue by DylanPiercey** [andrewplummer/Sugar#463]
Similar to String::endsWith(find, pos, case)

I think String::has should have optional case insensitivity. Anyone agree?

**Comment by andrewplummer** [comment]
Note that String#has was deprecated in favor of String#contains to keep up with the ES6 spec. That spec has now changed, however, and is now String#includes. This method finds one string inside of another, so it will be case sensitive always. The 2nd argument is position. More here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

Sugar provides a polyfill for `contains` currently. This will have to change to `includes`. Looks like this was revised in Dec 2014, so I feel slightly better about taking so long to release 1.5.0... Of course no guarantee that it will stay this way, and I will now have to consider whether or not to leave the polyfill out until the draft stabilizes.

**Comment by andrewplummer** [comment]
By "currently", I should say in edge, or what will be 1.5.0, which is not released yet, so String#contains is *not* currently part of Sugar yet.

**Comment by andrewplummer** [comment]
To update/summarize, the method will be `String#includes`. This method is in the ES6 spec and will throw an error if a regex is passed. Sugar polyfills this method and follows the spec exactly. However, the String package will "enhance" it further to accept regexes, which is basically just a shortcut to run `test` on the regex.

The milestone for this is now v2.0.0. This version features a major change which is that all prototype extension will now be opt-in. When doing this, "enhancing" methods can be a controversial choice (Sugar also "enhances" Array find methods to allow passing non-function arguments which the native versions do not accept), so a flag will allow you to opt out of this behavior (while still extending other methods):

```
Sugar.extend({
  enhanceString: false
});
```

Not absolutely 100% on the `enhanceString` naming yet, but it will be something like that.

**Comment by Mouvedia** [comment]
@DylanPiercey https://github.com/Mouvedia/String#has
