### ISSUE TITLE
Expose operators as functions?

### ISSUE THREAD

**Issue by vendethiel** [andrewplummer/Sugar#465]
Something I **really**, **really** miss in SugarJS and I have in LS: operators as functions.

i.e.:

```
["1.4", "2.3", "5", ""].map(unary('+'))
```

Not sure how it should look like. But please :). In LiveScript, I can just do `(+)` (works wonders with sugar, though I really like prelude-ls that's meant to be used with it)

**Comment by andrewplummer** [comment]
How are you envisioning this working, as you have a global method `unary` right now, which is not something that Sugar does.

(sorry for the long delay in responding btw)

**Comment by vendethiel** [comment]
Not sure. `Function.new('+')`? `Function['+']` ? But then it's unary vs binary. Not sure it'd fit in sugar, after all...

**Comment by andrewplummer** [comment]
Hmm... `Function['+']` is kind of interesting...

I'm not entirely sure what you meanby "then it's unary vs binary"?

Also, what would be the result of the first example you gave?

**Comment by vendethiel** [comment]
`Function['+']` could either mean `x + y` or `+ y`

and then we have two choices : 

- do we want it to curry
- do we want it to dispatch on arity

if we go for the first, `Function['+'](1)(2)` would be 3.
If we go for the second, `Function1['+'](1, 2)` would be 3, but `Function['+']("0.5")` would be `0.5`

the idea here was to `parseInt` on those, so the curry version looks more interesting.
This means that

`["1.0", "3.4", "5.4"].map(Function['+'])` would be an array of 1-ary functions (waiting to receive their 2nd argument).

**Comment by andrewplummer** [comment]
Which is LS, curry or dispatch?

**Comment by vendethiel** [comment]
LiveScript does curry, but then, `(0+)` compiles to a 1-ary function that does what I want :-).

**Comment by andrewplummer** [comment]
Right...  I gotta be honest, these are kinda special. I know they can be super useful but the learning curve seems kinda steep compared to their usefulness. I know they have high general applicability, so there's probably a lot I'm not thinking of... Maybe you have some other real world examples?

For example in this case you now Sugar let's you simply say:
```
["1.0", "3.4", "5.4"].map('toNumber')
```

**Comment by vendethiel** [comment]
that seems okay :)

**Comment by andrewplummer** [comment]
That said, it's doing more than just a parseInt. It actually checks for decimals and does a parseInt vs. parseFloat accordingly (also handles full-width numerals as well). This is likely overkill for someone who knows what they want to do. One solution might be to add `toInt` and `toFloat` methods to Number just as straight shortcuts, although I'm often hesitant about adding more methods they seem like they would add value here.
