### ISSUE TITLE
Parsing invalid dates not working as expected

### ISSUE THREAD

**Issue by patja** [andrewplummer/Sugar#466]
I expect Date.create('02-35-2014') (and any other invalid combinations) to return isValid() = false.

It returns a date of Friday March 7th, 2014 00:00:00.000

it can be reproduced here:  http://sugarjs.com/dates as well

**Comment by andrewplummer** [comment]
Sorry for the delay here. No, Sugar intentionally allows overshooting of dates as it internally uses the `setDate`, etc methods which allow overshooting as well. This actually allows for a lot of flexibility when incrementing.

I suppose some kind of "strict mode" might be possible, however this would get hairy very fast as there's a wide range of cases to account for... for example what about February 29th? What about 11:39pm on a day that has a DST shift?

**Comment by andrewplummer** [comment]
Going to close this one out for now. Feel free to reopen as needed.
