### ISSUE TITLE
UTC Dates out of sync with native JS Date functions (documentation issue?)

### ISSUE THREAD

**Issue by DarrenCook** [andrewplummer/Sugar#469]
```
var d = Date.create().utc();
console.log(d.getHours().pad(2));
console.log(d.format("{HH}"));
```

The first line says "18" whereas the second line says "17". (I'm in "BST" as I test this, hence the 1hr difference, I think in "JST" you'd see "02" vs. "17"?) The "17" is the output I expected.

I suspect this may be tough? In which case how about a distinct line in the UTC Dates section of the documentation, something like: "The native getXXX() functions will continue to use your browser timezone, do not use them if using `utc()`"  ?

**Comment by andrewplummer** [comment]
Good point. Will update the documents to be clearer about this.
Also sorry for taking so long to respond!
