### ISSUE TITLE
Array creator method that accepts a per-element construction function

### ISSUE THREAD

**Issue by lolmaus** [andrewplummer/Sugar#471]
In Ruby you can create an array by passing to `Array.new` the following:
- a number of items
- a constructor function that creates a single element of the array and accepts its index

Example:

``` rb
foo = Array.new(4) { |index|
  index ** 2
}

# => [0, 1, 4, 9]
```

It is extremely convenient.

Sugar happens to have its own array [constructor](http://sugarjs.com/api/Array/create), but it's kinda useless. :(

My current workaround with CoffeeScript is the following:

``` coffee
foo = [0..4].map (index) ->
  index * index

# => [0, 1, 4, 9]
```

It works perfectly, but it's harder to grasp. I prefer my code to be as self-explanatory as possible.

My suggestion is to create a new method working like in Ruby:

``` js
Array.construct( 4, function(index) {
  return index * index;
});
// => [0, 1, 4, 9]
```

I would suggest doing that for the existing `.create`, but there seems to be no way to do that without breaking compatibility. :(

**Comment by andrewplummer** [comment]
Hmmm... I see the issue.
This is a shame because `new Array(4).map()` is a perfect solution that parallels ruby, however it doesn't work because Javascript array functions intentionally don't visit members of sparse arrays.

Given that, I think the more elegant solution is the one in the referenced issue of using `times` instead and having it return the array. Alternately `Array.times` could be used for this as well if that makes more sense.

Note that `Array.new` will not work in IE as it is a reserved keyword.

**Comment by jbmonroe** [comment]
This works, although it only makes shallow copies of arrays passed as population values.

    if (!Array.construct) {
        Array.construct = function (arg0,arg1)
        {
            var i,
                ret = [],
                t0 = typeof arg0,
                t1 = typeof arg1;
            if (t0 === "number") {
                if (t1 === "function") {
                    for (i = 0; i < arg0; ++i) {
                        ret[i] = arg1(i);
                    }
                } else {
                    if (t1 != "undefined") {
                        if (Array.isArray(arg1)) {
                            for (i = 0; i < arg0; ++i) {
                                ret[i] = arg1.slice(); // Need a copy, which will be shallow if the array contains objects
                            }
                        } else {
                            if (t1 === "object") {
                                arg1 = JSON.stringify(arg1);
                                for (i = 0; i < arg0; ++i) {
                                    ret[i] = JSON.parse(arg1); // Need to make a new one each time; slow, but deep.
                                }
                            } else {
                                for (i = 0; i < arg0; ++i) {
                                    ret[i] = arg1;
                                }
                            }
                        }
                    } else {
                        for (i = 0; i < arg0; ++i) {
                            ret[i] = undefined;
                        }
                    }
                }
            } else {
                if (t0 === "function") { // Signature is bool fn(index,array)
                    i = -1;
                    while (arg0(++i,ret));
                }
            }
            return ret;
        };
    }

**Comment by andrewplummer** [comment]
This is now touched upon by the ES6 spec. `Array.from` is designed to create arrays from array-like structures. It also now [visits sparse array members](https://bugs.ecmascript.org/show_bug.cgi?id=2562) so this should address your issue and make creating new arrays a-la Ruby very clean:

```
Array.from(new Array(4), function(el, index) {
  return index * index;
});
```

Sugar is currently in the middle of a major rewrite and although it's not finalized yet `Array.create` will likely be removed and `Array.from` polyfilled instead. This should address your issue I think.

**Comment by andrewplummer** [comment]
OK this will go out in the next version! Sugar will now polyfill `Array.from` by default. Note that there will be a new build system as well, so if you're already using an ES6 polyfill the es6 package can be removed.

**Comment by andrewplummer** [comment]
Although I think the syntax is pretty good as is, I am willing to consider an `Array.construct` if you still think it would be useful for you. So:

```
Array.construct(4, function (index) {
  return index * index;
});
```

Would essentially be a shortcut for:

```
Array.from(new Array(4), function (el, index) {
  return index * index;
});
```

Not much of a savings, really, but I think the semantics are cleaner and it reads better. Also note that the `el` will always be undefined, so the first argument should probably be the index.

**Comment by lolmaus** [comment]
:+1:
