### ISSUE TITLE
daysSince changing at wrong time

### ISSUE THREAD

**Issue by brentonhouse** [andrewplummer/Sugar#474]
The daysSince() method (and example on website) is changing at 10pm CST for me instead of 12am.  I am in CST timezone.

If this function runs after 10pm CST it increments the result:
Date.create().daysSince('7/1/2014')

Date.create('11/10/2014 21:00:00').daysSince('7/1/2014') --> 132
Date.create('11/10/2014 22:00:00').daysSince('7/1/2014') --> 133

**Comment by andrewplummer** [comment]
This appears to be due to a couple of factors. First, the span between July and November is traversing DST, so the calculation of milliseconds is losing 1 hour there. Also there is a rounding error being applied as well. However it seems that I'm applying this error too broadly. Of course this is a bug, but I need to think of a different approach here.

**Comment by andrewplummer** [comment]
Ok, now that was an awesome bug. You scratched the surface of a sore point with relative dates, which is the fact that simply using multipliers to handle traversal of different units leads to ambiguity. There are 3 main ambiguous parts:

- 1 year is not always 365 days (leap years)
- 1 month is not... well not anything. It changes.
- 1 day is not always 24 hours (DST traversal, like in your case)

Previously, Sugar was handling this by a system of error margins per unit (.999 in most cases, .919 for months, which roughly covered the deviation of 28 - 31 days and applying clever rounding to compensate. However your bug exposed the main problem with this, which is that rounding can cause unexpected issues like the one you were having, so it had to go.

Instead, the new system uses the same multipliers for units of `hours` or lower (which are guaranteed to be constant), but higher order units traverse the gap using the internal `set[unit]` methods. This means that "1 month from January 22" is now "February 22", not  "30.4375 days after January 22", which is far more faithful to what most people are expecting, and all of the error compensation for that problem can go out the window.

The traversal probably does take a bit of a performance hit compared to straight multiplication, but I've done some optimizations and it should definitely be worth it.

**Comment by brentonhouse** [comment]
awesome!  thanks so much!!
