### ISSUE TITLE
Get full regexp of dates

### ISSUE THREAD

**Issue by AdamPietrasiak** [andrewplummer/Sugar#475]
Hi! First of, Dates of Sugarjs is amazing and I'm really glad you've made it!

What I need to do is to parse date in longer text. 

"Some text some text next friday more text"

I need to separate it to 3 parts "Some text some text" "next friday" and "more text" and then know that "next friday" part is recognized as date and parse it.

What I need is full regular expression of anything that SugarJs dates is able to parse.

Then I would be able to make something like myTextString.split(datesRegexpObject);

Is it possible to get it somehow?

edit: it would basically be http://sugarjs.com/date_formats this table joined as regex

**Comment by andrewplummer** [comment]
Duplicate
