### ISSUE TITLE
Add String.format function.

### ISSUE THREAD

**Issue by lygstate** [andrewplummer/Sugar#476]
That's used very often.

**Comment by andrewplummer** [comment]
Examples?

I went nuts with aliases when Sugar first started and regretted it a lot. It usually causes more confusion than it solves. Also, I'm sure I visited it when the method was first created. Actually I remember mulling over that one for a long, long time, and I felt in the end that `assign` is very expressive as to what the method does.

**Comment by andrewplummer** [comment]
Actually looking at the issue, Python's `String#format` follows `assign` almost exactly. To be honest I wasn't aware of this before. Maybe that is a good case for changing the name? I felt that `assign` was appropriate before but now it seems that  `format` would be more readily understandable?

**Comment by grofit** [comment]
.net uses `Format` as well, but its 0 based on indexes not 1 based, I just ended up using assign in the end, its just I had to come find this thread before I realized it existed.

**Comment by andrewplummer** [comment]
Actually looks like Python is 0 based as well... maybe this is better?
Sugar is in the middle of a rewrite... if changing it is better then now is the time.

**Comment by andrewplummer** [comment]
FYI my reasoning for being 1 based originally was that Regex replacement tokens are as well (i.e. `.replace(/(abc)/, '$1')` ... so much for consistency....

**Comment by grofit** [comment]
yeah I can see that angle of it, but for consistency I would probably go with 0 based indexes but again it is your library so you do what you think is right, I currently wrote the code base to use 1 based indexes but I guess its not a huge task to change back to 0.

**Comment by andrewplummer** [comment]
I think that if we keep it as `assign` 1 based indexes is OK, but if it changes to `format` then 0 based indexes should be used for consistency.

The question is do you think `format` is more expected/easier to guess?

**Comment by grofit** [comment]
yes, I think almost every language/platform has the notion of string format, be it `s/printf` or `format` and in most cases they work off zero based indexes, so personally I would generally expect most frameworks to use `format` and be zero indexed by default.

So if you have assign keep legacy behavior and format do more in line with other frameworks (zero based) then I think you have the best of both worlds.

**Comment by andrewplummer** [comment]
Well I think it's much more of a mixed bag. Most languages have something like `sprintf` which don't rely on numbered tokens but instead position. This can be limiting however. The power of assign/format is that it can handle named arguments inside an object (which python can also do), and in keeping in line with that indexes are simply named arguments for arrays. However, following that line of thinking it makes no sense for them to be 1 based, and in fact the code itself has a check for "objectType" that is looking more and more silly to me now. Any change that can reduce code also tends to be one that is more intuitive for users and I'm all for that.

However I'm very much against method creep, and I definitely don't want to keep both if it's at all possible. It doesn't seem that assign is doing anything above and beyond python's `format` so I have no problem removing `assign` if we change the name.

**Comment by andrewplummer** [comment]
Okay this will be in the next major release. Aside from the renaming, the most major difference is that `String#format` will use zero based indexes. There was also a lot of work to bring it in line with Python as I wanted it to throw errors when tokens cannot be parsed, etc. Also you can escape braces now with `{{` or `}}` which is something `assign` never even thought about. Very clean implementation considering though, and did some benchmarks on it to make sure the performance is good.

**Comment by andrewplummer** [comment]
Just to note as a disclaimer however, `format` in Python is doing much more, some useful, some frankly a little bizarre. This is intended as a subset of that behavior.

**Comment by andrewplummer** [comment]
Note, this has dovetailed very nicely with issue #472. The implementation is exactly the same as described above, but now it will support deep properties with the `.` operator. For example:

```
"You live on: {profile.address.street}".format(user);
```

It also supports array key indexes, so formatting with complex data *without* merging (which was what Sugar was previously doing) should now be a breeze:

```
"User {0.profile.username} just sent a message to {1.profile.username}".format(actor, actee);
"User {0.profile.username} just sent a message to {1.profile.username}".format(users); // alternate
```

**Comment by andrewplummer** [comment]
Ok! This is out now!
