### ISSUE TITLE
Strip/Remove from left/right?

### ISSUE THREAD

**Issue by grofit** [andrewplummer/Sugar#478]
I am porting from a set of string based functions I wrote to sugar, and everything else exists but there seems to be no method for removing characters from the start or end of a string. You could do the inverse of it by doing:
```
var myValue = "some, comma, separated, values,";
var correctValue = myValue.to(myValue.length-1);
```
However it would be good if you could just do this with inline strings like:

```
var correctValue = "some, comma, separated, values,".removeFromRight(1);
// Or
var correctValue = "some, comma, separated, values,".remove(-3); // - for right + for left
```

If there is anything that existing to do this already I cannot seem to find it.

**Comment by andrewplummer** [comment]
Well, `to` and `from` both accept negative parameters as well so you could just say:

```
var correctValue = "some, comma, separated, values,".to(-1);
```

Does that not work?

**Comment by grofit** [comment]
Sure should work if it supports negative.
