### ISSUE TITLE
duration granularity

### ISSUE THREAD

**Issue by fiznool** [andrewplummer/Sugar#485]
Right now, the `Number.duration()` function returns a single unit. For example, the following both return _1 week_:

```
(604800000).duration(); // -> '1 week'
(864000000).duration(); // -> '1 week'
```

It would be nice if you could pass in a 'granularity' argument which would (e.g.) allow the second result to be `1 week, 3 days`.

**Comment by fiznool** [comment]
I guess once you get into months, this becomes difficult. I've created a simplified, English-only, up to 'weeks' function [here](https://gist.github.com/fiznool/2e82e0b7380cd3327b49) that could be used for reference.

**Comment by andrewplummer** [comment]
Have a look at the `Date#relative` function. This lets you to pass a function that gets passed special arguments and allows for special edge cases. It should be easy to hook up `Number#duration` to do the same thing as they are very similar methods and also maintain some parallelism in the process.

**Comment by andrewplummer** [comment]
Note that the function also gets passed the localization object which should help with handling other locales as well.

**Comment by andrewplummer** [comment]
Does this solution work for you? If so I can close this out.

**Comment by andrewplummer** [comment]
Closing this one out for now. Please feel free to reopen if it's not working for you.
