### ISSUE TITLE
Object.isNumber() behaves strangely when passed NaN

### ISSUE THREAD

**Issue by gilest** [andrewplummer/Sugar#487]
Using Sugar 1.4.1

```JavaScript
Object.isNumber(NaN); // -> true
```

By definition, one would think that NaN is probably not a number :smile:

**Comment by andrewplummer** [comment]
Actually, it is:
```
typeof NaN
  -> "number"
```

Welcome to the awesome world of Javascript :)

**Comment by gilest** [comment]
:+1:
