### ISSUE TITLE
.cancel() ignored

### ISSUE THREAD

**Issue by zamb3zi** [andrewplummer/Sugar#488]
Hi,
I'm having trouble with a simple fn.every(ms) call. The function is unable to cancel itself in a straightforward way. Please see the following node.js example:

``` javascript
require('sugar');
var i=0;
var h = (function(){
    console.log(++i);
    if(i>=3) {
        console.log('stop');
        h.cancel(); // silently ignored.
        h.cancel.delay(0); // silently ignored.
        (function(){h.cancel()}).delay(0); // works.
    }
}).every(1000);
```

A straightforward use of setInterval/clearInterval works fine, so I've switched to that for now.

**Comment by andrewplummer** [comment]
Excellent catch. This was indeed a bug and has been fixed!

**Comment by zamb3zi** [comment]
Awesome! Thanks.
