### ISSUE TITLE
Abbreviation of german weekdays

### ISSUE THREAD

**Issue by thomasf1** [andrewplummer/Sugar#489]
The appreciated form of german weekdays usually uses 2 characters instead of the 3 characters in english.

en -> Mon, Tue, Wed
de current -> Mon, Die, Mit
de usually -> Mo, Di, Mi

Would you guys be interested in a fix for that?

**Comment by andrewplummer** [comment]
Yes this is something I can handle. To be clear though, are you referring to the `{dow}` token in `Date#format`, or the ability to parse dates with 2 character abbreviations on creation? I'm guessing that both should probably be supported?

**Comment by thomasf1** [comment]
Hey Andrew, thanks for your response.

Yea, I´d say both should be 2 characters. That´s at least the standard for abbreviating dates in Germany.

We did create a patch, but then figured out that the {dow} seems to be separate from the code that inits the language setup.

So we´ve fixed it in the end with a switch in the app code currently...

**Comment by thomasf1** [comment]
PS: Attached a screenshot of the Calendar app in OSX (english OS / German regional setting):
![screen shot 2015-04-06 at 16 14 09](https://cloud.githubusercontent.com/assets/937467/7005424/27dcb0ec-dc78-11e4-86f5-d123225d82b1.png)

**Comment by andrewplummer** [comment]
Yes {dow} was hard-coded to 3 chars (with the subtle feeling that this probably wouldn't work for all locales but we'd "cross that bridge when we come to it").  Will have a look at this one! Thanks.

**Comment by andrewplummer** [comment]
Also, what about Month abbreviations?

**Comment by andrewplummer** [comment]
Also sorry... just to be perfectly clear are you saying that they are ALWAYS abbreviated to 2 characters, or just "usually"?

**Comment by andrewplummer** [comment]
Ok I've started with a fix for this. Parsing for now will assume 2 characters for weekdays only. If we need to support 3 characters also and/or months as well I'll have to do some more work.

For date formatting, I've added 2 tokens `{do}` and `{Do}` so that slicing to 2 characters is now possible in any language.

**Comment by andrewplummer** [comment]
Ping.... can I get an answer to the above 2 questions? Would like to make this a complete fix...

**Comment by thomasf1** [comment]
I´l have a look... Thanks!

**Comment by thomasf1** [comment]
Just had a look... 

Doesn´t seem to be included in the release branch of the current master, and there seems to be no dev branch...

Was trying:
```javascript
Date.create("yesterday").format('{{Do}} {{yyyy}}')
```

**Comment by andrewplummer** [comment]
It's working for me... branch is master and that format produces `Su 2015`. Make sure you're loading `release/sugar.min.js`
