### ISSUE TITLE
new Date().rewind inconsistency

### ISSUE THREAD

**Issue by djgadd** [andrewplummer/Sugar#492]
Playing with the little demos in the API documentation and it looks like the Date.rewind() function isn't working properly (or it's not giving me an expected result):

https://jsfiddle.net/p33k3vx3/

Rewinding a week is as expected, rewinding a day is as expected, but rewinding a week and 1 day (which I'd expect to be 8 days) rewinds 9 days. It looks like a bug to me but if it is intentional it should be documented.

**Comment by andrewplummer** [comment]
Nope, that most certainly was a bug. Just committed a fix.

**Comment by vendethiel** [comment]
(maybe `1.5.0` would be better as a milestone instead?)

**Comment by andrewplummer** [comment]
Thanks, just set it!

**Comment by djgadd** [comment]
Awesome thanks Andrew.
