### ISSUE TITLE
isBefore(null) sometimes returns true in Firefox

### ISSUE THREAD

**Issue by p0deje** [andrewplummer/Sugar#494]
Calling `isBefore()` with `null` returns `false` most of the time, but sometimes - `true`. The problem is easily reproducible in Firefox console.

```javascript
(new Date()).isBefore(null);
=> true
```

Tested with:
* Sugar 1.4.1
* Firefox 30 (OS X)

UPD: It can be reproduced in Chrome 41.0.2272.118 but it occurs less frequently.

**Comment by andrewplummer** [comment]
Will have a look... thanks for this!

**Comment by andrewplummer** [comment]
Hi, can you confirm that this is still happening? Thank you!

**Comment by p0deje** [comment]
Tested against latest release and cannot reproduce anymore.

Thanks!
