### ISSUE TITLE
forgot to update the doc [has > contains]

### ISSUE THREAD

**Issue by Mouvedia** [andrewplummer/Sugar#502]
http://sugarjs.com/api/String/has
cf 9df9ec01f06ccc45b7dbecd90eabef13b25c1f48

You could keep it as an alias.
#463 is related.

**Comment by andrewplummer** [comment]
This will be affected when 1.5 goes out (will update all the docs at that time).

**Comment by andrewplummer** [comment]
Just a quick note, old version docs are now supported on the site. Look for the little vertical "..." next to the menu bar to change the version.

**Comment by Mouvedia** [comment]
@andrewplummer I am not seeing `contains` mentioned in either versions though.

**Comment by andrewplummer** [comment]
Ah sorry. I commented in #463, but forgot to comment here as well. `has` is now `includes` in v2 but is a polyfill for the ES6 method. `has` will continue on in v1 as is.  The original change you commented on has moved on, but `contains` was effectively reverted.
