### ISSUE TITLE
blog.sugarjs.com not resolving?

### ISSUE THREAD

**Issue by jikamens** [andrewplummer/Sugar#506]
title says it all

**Comment by andrewplummer** [comment]
Thank you!! I changed hosts recently and didn't catch this. Should be ok now.

**Comment by andrewplummer** [comment]
Actually, not sure it worked... are you seeing on your end?

**Comment by jikamens** [comment]
It looks like it's working.

**Comment by andrewplummer** [comment]
Same here. Thanks for this!
