### ISSUE TITLE
Date.create('Sept 2015') works in Chrome, not FF or IE

### ISSUE THREAD

**Issue by jbthoma** [andrewplummer/Sugar#507]
Works fine in Chrome, return Invalid Date in FF and IE.

**Comment by andrewplummer** [comment]
In Sugar months are parsed as either full months (`September`) or abbreviated month (`Sep`) ... `Sept` is not one of the tokens, so this is falling through to native browser dates (`new Date('Sept 2015')`) which, it seems, Chrome supports but firefox does not.

So let's think about this:
```
Janu
Febr
Marc
Apri
May
June
July
Augu
Sept
Octo
Nove
Dece
```

I would argue that none of these are standard ways of writing a month except for "Sept" (and "June/July" of course, but that's parsed as a full date). Sept I agree is not unheard of, but is it common enough to support?

**Comment by jbthoma** [comment]
Common enough to support?  Hmm...I would probably argue that Sept is far more common than Sep.  I googled "abbreviate september" and it confirms my theory.  Sept is definitely the recommended abbreviation for September.

**Comment by andrewplummer** [comment]
Ok, I would definitely use `Sep` over `Sept`, but can't argue with your Googling logic. There are a few other threads on this as well... I'll see what I can do!

**Comment by andrewplummer** [comment]
Ok this should work in the next version!

**Comment by jbthoma** [comment]
Awesome!  Thank you!  I could not imagine what I'd do without SugarJS in my toolkit.
