### ISSUE TITLE
Add `String.Inflect`method

### ISSUE THREAD

**Issue by cdeutsch** [andrewplummer/Sugar#508]
It would be nice to have access to the `inflect` method directly so you can easily conditionally pluralize words.

Example:

```
var message = "One " + "user".inflect(users.count) + " selected.";
```

Maybe there is an existing way to do this that I missed?

**Comment by krnlde** [comment]
How do you want to implement languages?

**Comment by krnlde** [comment]
Consider https://github.com/sindresorhus/gulp-rev

**Comment by andrewplummer** [comment]
I think that's a great idea. Is `inflect` the best method name here? Do you have an idea about what is standard?

@krnlde The Sugar inflect package is already English-only so this isn't new functionality but exposing what already exists. For locales a proper i18n library should be used instead.

**Comment by andrewplummer** [comment]
Ok, I've added this feature. By far the easiest implementation (and I think the most straightforward naming) is simply to allow a numeric parameter on the `pluralize` method allowing for conditional pluralization, which was also quite easy.

Note that this method will not output the number itself in any way to allow for maximum flexibility (Imagine someone wanting to display the number in roman numerals or something nuts like that).
