### ISSUE TITLE
Date.create() does not accept "a" or "p" as an am/pm string

### ISSUE THREAD

**Issue by mventimi** [andrewplummer/Sugar#509]
I'd like to be able to create dates using an "a" or "p" suffix. Right now, the behavior is as follows:

```
Date.create('Wednesday 3:00pm') > "Wednesday, September 2, 2015 15:00"
Date.create('Wednesday 3:00p') > "Invalid Date"
```

This is not consistent with the use of `{t}` in the .format() call:

```
Date.create('Wednesday 3:00pm').format("{h}:{mm}{t}") > "3:00p"
```

**Comment by andrewplummer** [comment]
This makes sense to me. Will have a look.
