### ISSUE TITLE
Excuse me, have docs with PDF?

### ISSUE THREAD

**Issue by thearabbit** [andrewplummer/Sugar#510]
Excuse me, have docs with PDF?

**Comment by andrewplummer** [comment]
Sorry no. There is a JSON file however! ... not sure if that helps you :)

**Comment by thearabbit** [comment]
I would like to print it.

**Comment by andrewplummer** [comment]
OK how's this... I added print styles to the site just now so that the full method description isn't hidden anymore when printing. You should be able to print out the docs, although you'll have to print out each tab separately.
