### ISSUE TITLE
weekday at loose digit fails.

### ISSUE THREAD

**Issue by silentrob** [andrewplummer/Sugar#513]
`Sunday at 3:00` works gh-210
`Sunday at 3` does not work 
```
Date.future("Sunday at 3");
Thu Mar 01 2001 00:00:00 GMT-0800 (PST),
```

**Comment by andrewplummer** [comment]
"loose digits" as you call them create a lot of ambiguities that may not be able to co-exist with other date parsing formats. I will have a look though. Also note this relates to #509.

**Comment by andrewplummer** [comment]
Had a look at this. It seems like it can be done, but "Sunday at 3" is going to have to mean "Sunday at 3am". I'm not sure if this ambiguity is what you were looking for but I don't think there is any other way to define it with any kind of authority such that edge cases wouldn't be unexpected...

**Comment by silentrob** [comment]
Ya I think that is better then the result we are getting, at least the day portion is right, I'm envisioning a time context were time values defaults into some standard deviation leaning more heavely around "work hours" 9 - 5, but there could be other conext as well. Im still brainstorming this, and that would be outside the scope of sugar dates.

**Comment by andrewplummer** [comment]
Imagine `Sunday at 8`. I don't see any way this would not only be ambiguous but pretty much also split opinions right down the middle as well as be completely dependent on context (and even then probably ambiguous). I'm actually a little bit questioning the utility of allowing this format. At first I thought it would still have utility as the user could manipulate the date after it's parsed... something like:

```
var d = Date.create(userInput);
if (d.getHours() < 8) {
  d.advance({ hours: 12 });
}
```

However after thinking about it most use cases would be allowing anything Sugar can parse for `userInput`, so it wouldn't make sense to advance *any* date, meaning they would probably have to catch that format ahead of time anyway. If that's going to be the main use case, then I think it would be better to disallow this format and let each application handle however it wants to.

**Comment by silentrob** [comment]
I agree.. `Sunday at 8` is both 8AM and 8PM and really the best you can do is return an array of suggested dates... but again that is outside the scope of what sugar is trying to do.

Threre is no doubt that dates / times and natural language is a hard hard fuzzy problem and remains still somewhat unsolved. I also think the key to cracking it is to have better date primitives, like ranges. For example IMO `Last month` should be a range rather then a single date, and same for `after dinner` with it auto clamping to midnight. 

Thanks for your thoughts and feedback.

**Comment by andrewplummer** [comment]
That's actually a really interesting idea... Sugar does have Date ranges, but you're right that the fuzziness there is tricky and out of scope (and probably very context-sensitive).

Anyway I think I may go ahead and revert this change as I don't think it has the utility I initially thought. Formats like `tomorrow at 3pm`, `tomorrow at 3:00pm` and now `tomorrow at 3p` will still be supported, of course.

**Comment by andrewplummer** [comment]
Ok this is reverted now. I think I will close it but feel free to comment or reopen if there's something more.
