### ISSUE TITLE
Docs: "Source" link points to wrong source code lines on GitHub

### ISSUE THREAD

**Issue by vinogradov** [andrewplummer/Sugar#516]
Hi.
The **Source** link on the [API Documentation](http://sugarjs.com/api/Function) page (which is located at the bottom of each function description)  points to wrong source code lines on GitHub (at least for [Functions](http://sugarjs.com/api/Function))

![](https://dl.dropboxusercontent.com/u/9482644/Screen%20Shot%202015-09-30%20at%2016.01.21.png)

**Comment by andrewplummer** [comment]
Hi, thanks for this!

I think it's because I'm linking to the "master" branch which gets out of sync. There's a big release coming up so I'll make sure it links to the right version blob at that time.

Thanks!

**Comment by andrewplummer** [comment]
Actually scratch that... this was a very minor fix so just fixed it!
