### ISSUE TITLE
Docs: "Object." prefix is missing before function names in titles

### ISSUE THREAD

**Issue by vinogradov** [andrewplummer/Sugar#517]
On the [Object documentation page](http://sugarjs.com/api/Object) some function names go without **Object.** prefix (if you unfold the description it will be there in code examples though), for example [clone](http://sugarjs.com/api/Object/clone) title:

`clone(obj, deep)`

should be

`Object.clone(obj, deep)`

**Comment by andrewplummer** [comment]
It's actually because they're both static and instance methods depending on the context. However this definitely could be clearer, so I'll have a look at it.

**Comment by andrewplummer** [comment]
Closing this for now. I've added a new [Object methods](https://sugarjs.com/docs/#/ObjectMethods) section in the docs that now hopefully better helps explain the issue. Thanks!
