### ISSUE TITLE
Date.create fails to parse Russian date strings

### ISSUE THREAD

**Issue by smurali31** [andrewplummer/Sugar#524]
Windows Long Date format displays Russian strings as follows:
3 октября 2014 r.
Sugarjs however fails to parse this string

Same goes for "2015년 11월 24일 화요일" in Korean.

**Comment by andrewplummer** [comment]
Well I'm curious... for Russian what you posted was a Latin "r", but the Russian is a different letter entirely so that can't be right... I copy/pasted your example and was scratching my head before I figured it out. In any case I added handling of these formats.

**Comment by smurali31** [comment]
Excellent. Thanks, Andrew. What I copy pasted was the string that you can find in Windows Region and language settings by changing your region to Russian. You can also get the same string by doing the following with C#

CultureInfo ci = new CultureInfo("ru-RU");
	Thread.CurrentThread.CurrentCulture = ci;
	Console.WriteLine(DateTime.Now.ToLongDateString());

Btw, when is this expected to release?

**Comment by andrewplummer** [comment]
hahah... I'm not saying you're wrong, but if that were true it would be an epic bug (I get the right character in XP/7... don't really have access to C#).

Expected release is very soon! And please don't go around looking at the timestamps of my comments on other issues because this time I really mean it!

**Comment by smurali31** [comment]
seems like 1.5.0 has the fix too. Can you please confirm?

**Comment by andrewplummer** [comment]
Sorry, the next version of 1 was going to be `1.4.2` but will now be `1.5`, (I changed the label name, but it didn't update inline it seems). Yes, this fix will be included.

**Comment by smurali31** [comment]
Excellent! Thanks

**Comment by smurali31** [comment]
Is 1.5 a stable version? http://sugarjs.com still points to 1.4.1

**Comment by andrewplummer** [comment]
It's not released yet. Will be release with the same timing as `2.0.0` -- a few backward compatible changes and bugfixes like this one.

**Comment by smurali31** [comment]
Just wondering where we are w.r.to 1.5 release? You mentioned "very soon" :-)

**Comment by andrewplummer** [comment]
Hello, yes things are snowballing together and delays keep happening, however I'm still doing everything I can to try to live up to "very soon". Sorry can't really be more specific than that but will do my best!

**Comment by muralidhars** [comment]
Hey Andrew - How is the release looking? Sorry to be persistent..

**Comment by andrewplummer** [comment]
So I really wanted to get everything together this weekend but a lot of small flames left to stomp out. However this is mostly around the site/documentation. Meanwhile the tests are passing across the board and I've pushed the latest build... let's call it RC-1. Maybe you'd like to be first to try it out?


https://github.com/andrewplummer/Sugar/blob/master-2.0.0/sugar.js
https://github.com/andrewplummer/Sugar/blob/master-2.0.0/sugar.min.js

**Comment by vendethiel** [comment]
:+1:
