### ISSUE TITLE
Array#dig and Hash#dig from Ruby 2.3.0

### ISSUE THREAD

**Issue by jonathanhefner** [andrewplummer/Sugar#528]
Ruby 2.3.0 added the [Array#dig](http://ruby-doc.org/core-2.3.0/Array.html#method-i-dig) and [Hash#dig](http://ruby-doc.org/core-2.3.0/Hash.html#method-i-dig) methods, and they seem like they would be a great fit for Sugar.js.  Thoughts?

**Comment by andrewplummer** [comment]
This is actually going to be supported in 2.0.0 (issue #472)! In addition to the main 2 new methods `Object.get` and `Object.set`, a number of supporting methods will also use this deep syntax.

**Comment by andrewplummer** [comment]
Going to close this one out for now... Please re-open if that doesn't make sense.
