### ISSUE TITLE
Date.create() doesn't support dd/mm/yyyy

### ISSUE THREAD

**Issue by eshansingh** [andrewplummer/Sugar#534]
```js
Date.create('27/01/2016'); // => Thu Mar 01 2018 00:00:00 GMT+0530 (IST)
```

It's actually 27th January 2016. This kind of date format is very common in countries like India.

**Comment by deddu** [comment]
It seems that the date is being parsed using the en-us locale. That is mm/dd/yyyy . you can (and should) enforce the locale by passing the locale string as a second argument in the function. Date.create("27/1/2016", "en-UK") will work as you are expecting. Keep in mind that this is the cleanest solution to disambiguate between March first and January third.

**Comment by eshansingh** [comment]
Wow, that was so obvious. Thanks!

**Comment by andrewplummer** [comment]
Note that you can also pass `en-IN` as well if you like to be more explicit. Although there is no defined locale, it will have the same effect as `en-US` is the special one here.
