### ISSUE TITLE
npm install fails due to sugar-core 2.0.0 dependency

### ISSUE THREAD

**Issue by bgr** [andrewplummer/Sugar#539]
What is the recommended way to set up sugar dev env? I tried `npm install` (from 'master-2.0.0' branch), and got the following:
```
npm ERR! No compatible version found: sugar-core@^2.0.0
npm ERR! Valid install targets:
npm ERR! 0.0.1
```

**Comment by andrewplummer** [comment]
Ah sorry... that part isn't ready yet... I just removed that dependency so it should all work now.

**Comment by bgr** [comment]
Cool, works fine now. Got this warning though: 
`lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0`
might be wise to upgrade before the release of 2.0.0.
