### ISSUE TITLE
Better way to release memory from memoization routines

### ISSUE THREAD

**Issue by andrewplummer** [andrewplummer/Sugar#540]
As mentioned in #535, is there a way to either prevent memory from being trapped by internal memoization and/or allow users to release it? Methods discussed were:
1. `Sugar.purge`, freeing all memoized blocks. It may be beneficial to allow users to explicitly free all memory used, however forcing the user to control it manually is likely also a downside.
2. WeakMap, holding weak references to memoized objects. This way seems to be ideal, however is not available in all environments (namely IE10 and below). Additionally WeakMaps don't allow string primitives as keys. Does this defeat the purpose?
3. Other possibilities?

**Comment by ermouth** [comment]
Finally I ended up with not memoization, but cache. I mean a) precompiled entities have timestamp and hit counter, and b) cache has fixed upper limit and evicts least used or most old entries on significant overflow.

Not sure this approach is suitable for Sugar however.

**Comment by andrewplummer** [comment]
That seems like a reasonable method (it's basically memcache, no?) ... it's not necessarily UNsuitable for Sugar, however I hesitate to add too much complexity given that 1. if it has complexity then it should probably be exposed (shouldn't users be able to choose what the upper limit is and when to evict?) and 2. JS has limited low level access that it would be difficult to determine what the footprint of the cache is or how that relates to the overall environment... could "significant overflow" be determined in a non-arbitrary way?

Anyway thanks.... helps me to think about this!

**Comment by andrewplummer** [comment]
Ok, I did an audit of all methods that could potentially trap memory and how each of them should be approached:

### `String#format` and `Date#format`

These methods accept a format string demarcated with `{}`. Parsing out this format string every time can be expensive, so the format is parsed once and cached as an array of functions that the format string maps to.

### `Function#memoize`

This method returns a function that will only call once per "unique call". By default a unique call is one with the same number and value of all arguments. Additionally a hash function is accepted as an argument that will allow the user to redefine what a unique call is.
 
### `String#addAcronym`, etc.

The inflections module allows users to define acronyms that affect other string methods like `camelize`, `underscore`, etc.

### Holding of date parsing and formatting tokens in memory.

The date module has maps of parsing/formatting tokens etc.

### Compiled date locales.

Additionally compiled locales are held in memory mapped by their locale code.

-------------

Of these methods, only the 2 `format` methods explicitly qualify for this kind of memory purge system, while `memoize` is a bit tricky (more on that later). To first state the goal of this issue, it is to allow the release of memory that *could potentially grow without limit due to interaction with Sugar methods over a non-closed set of input*. To put it more simply, any functions that grow in parallel to user input when that input is not limited in scope.

First, this immediately disqualifies the above date internals as well as `addAcronym` etc. For date internals, these are either things like compiled tokens that are created on initialization, date format objects that are created when `addFormat` is called, or locales initialized by locale code. All of these are limited in scope, and do not grow with arbitrary user input. Some of these internals are "lazy loaded" or initialize only when a certain locale etc. is encountered, however they reach a limit and cannot grow beyond that, and so should not be considered. `addAcronym` etc. as well holds references to user input and can be though of as a "settings" object rather then a cache, so also does not qualify.

`Function#memoize` is interesting because it isn't doing internal memoization, instead it is exposing this functionality directly for the user. As this is part of a public API it would be strange to subject it to the same rules as internal memoization (whatever they may be). Additionally a memoized function's cache will disappear when the reference to the function itself is garbage collected, so there is a certain amount of control the user has in this regard. One possibility here would be to provide access to cache purging as part of the api for this method. For example, another argument could be a number that says "after N cached calls of this method, empty the cache". A separate number could be used for internal caches as well.

------------------------


Anyway this is just to list out potential targets for this method/mechanism. Next, I will think about how to implement.

**Comment by andrewplummer** [comment]
One more thing to note here is that WeakMap is not suited to this purpose, as its "weak keys" are based on reference, and so does not allow primitives. This means that it's not suited to standard caching/memoization routines that use string as canonical references. More about this [here](https://esdiscuss.org/topic/use-cases-for-weakmap) and [here](http://stackoverflow.com/questions/29413222/what-are-the-actual-uses-of-es6-weakmap).

**Comment by ermouth** [comment]
> it would be difficult to determine what the footprint of the cache is or how that relates to the overall environment... could "significant overflow" be determined in a non-arbitrary way?

Actually, footprint estimate is possible, but in any way it costs too much (both in terms of SLOC and CPU) if implemented for general use.

Although, as I‘ve written [here](https://github.com/andrewplummer/Sugar/issues/535#issuecomment-180810371) for 535 issue, for `String.format` and `Date.format` a cache entry could be an array of well observable size. So specialization gives predictability.

However under ‘significant overflow’ I mostly meant the size of cache that needs time to evict comparable to average template parse/run. I mean if we go into case we need to compact our cache, eviction in worst case only doubles time required for `.format` to run.

It gives an estimate of 500-1000 entries. To add, I usually evict half a cache at a time.

**Comment by andrewplummer** [comment]
I suppose that makes sense. I really wish that there was a better way than putting Sugar in the role of playing its own garbage collector here. This is far better left to browsers. I'm tempted to simply create the `purge` method and let applications handle instead, however I guess if you don't know about it then there's no difference from a memory leak...... agh....

Ok, I think I'll run some performance tests and decide on a reasonable upper limit for the current use cases....

**Comment by vendethiel** [comment]
I don't think it's a very good amazing to have sugar basically be an application itself on the side.

**Comment by andrewplummer** [comment]
Sorry... not sure I get what this means...

**Comment by vendethiel** [comment]
I mean you're adding basically application-range, and application-wide complexity to sugar: it needs information it doesn't have (what will be used, how often, etc). The application itself might know (specific list of format), and you need to setup callbacks at times, etc etc.

**Comment by andrewplummer** [comment]
Yep, that's why I'm quite hesitant to add it. What do you think? Would a manual `clearCaches` type function be enough? Other ideas?

**Comment by vendethiel** [comment]
Not sure. I'm not even positive it's Sugar's role to do its own caching, to be honest... If you need to "proxy" sugar's functions to add cache, it's not that bad (but the issue is that redefining them again on whichever object is a bit wonky...)

**Comment by andrewplummer** [comment]
Well, I think I would at least disagree with you there. I'm probably misrepresenting it by calling it "caching" in the first place, but some sort of memoization pattern should be common for utility libs I expect. This thread got started by `String#format` but let's set that one aside for a second and look at `Date#format` instead (the other potential target for this method). The concept of compiling tokens into an array of functions that would be stored with the format string as a key was an optimization directly "inspired" (ahem) by moment.js after looking at why Sugar was so much slower. It's now comparable in speed with moment and this is probably something that could not be achieved if it had to recompile the tokens each time. This is especially important considering how common the use pattern is of having a particular format you want to apply to many different dates.

**Comment by vendethiel** [comment]
Okay, that makes sense. I admit I don't remember the whole discussion. Would having a flag that says "please compile this one" make sense?

**Comment by andrewplummer** [comment]
Yeah, I'm getting a bit lost in the details too. I'll give a quick summary because I'm interested in your opinion on the matter as a whole:

@ermouth pointed out that the act of "memoization" for performance could be considered a memory leak as it retains memory without ever freeing it. His point was that this may be ok for client side applications but for server-side apps that can run indefinitely it's unacceptable. Although I'm sure many other libs do this, it's not an unfair point.

I opened this issue expecting to find a lot of places where Sugar is doing this, but actually did not. There are other points of memory retention such as compiled regexes for date formats in the date module, however it isn't the same concept as memoization and the objects do not grow as Sugar methods are called, but rather once on initialization of the format.

The two main methods I found that *could* expand memory as they are called are `String#format` and `Date#format`. This is because they both accept formats like `{a}, {b}` and retain the compiled format in memory as described above.

Considering that only these 2 methods would be affected, and that I don't have any idea if this is really an issue for anyone at the moment, I would really like to do something minimal for now. If actual complaints about memory leaks come in then it should be easy to update transparently.

I also would like to not burden the user with internals if at all possible, especially per-method. In a perfect world any memoized objects could be held weakly and leave freeing to the GC, but this doesn't seem possible for the time being....

**Comment by ermouth** [comment]
> I'm not even positive it's Sugar's role to do its own caching

It‘s not about role (whatever you mean), it‘s about performance. Your CPU, with its 3 layers of cache and TLB, does not have application role. Your network drivers are not ‘applications‘ in general sense despite they have DNS cache.

If you have a booster, that worth to be used constantly, you better put your booster under the hood.

**Comment by vendethiel** [comment]
Talking about cache levels of your CPU in a GC-collected world doesn't make sense at all. You have exactly zero guarantees WRT data locality, and no idea how many elements you can fit into your L1 anyway. No way to tell if your objects use open-addressing or other methods.
I think it's an important matter, but with a high-level language like JS you're often guessing the internal details.

**Comment by vendethiel** [comment]
I meant to specify that an application knows if a format will be reused a lot (most often) whereas sugar can't.

**Comment by andrewplummer** [comment]
> with a high-level language like JS you're often guessing the internal details

I do agree with this... if Sugar does implement something here it's going to be extremely simplistic *just* to prevent memory leaks from becoming an issue. I do not want to, nor am qualified to be in the business of guessing JS internals.

> an application knows if a format will be reused a lot whereas sugar can't.

I suppose you're right that generally an application knows better, however it's also possible that it may not know either. In any case, thinking about it is a burden I would really like to avoid confronting the user with as much as possible.

**Comment by andrewplummer** [comment]
Okay, thought about this a lot, and this is what I would like to do... No new method at all... instead internal caches will take the most naive approach possible that will get the job done, which is to simply keep a counter and clear the entire cache when the counter hits some reasonable but arbitrary number (500 or 1000 seem appropriate). Essentially it will be:

```
if (counter === 1000) {
  cache = {};
}
```

Here is why I think this works best:

1. It does the main job of preventing objects from arbitrarily expanding in memory.
2. It does not try to second guess the GC by forcefully calling `delete`. It simply releases the object reference which the GC is then free to collect.
3. It does not burden the user with having to make a decision for the sake of Sugar internals.
4. The cost of clearing the cache is zero as it doesn't have to step over entries. This means that calls to both `format` methods should never take longer than a non-cached operation.
5. Given the scope of this problem, a very simple solution seems to be appropriate (no over-engineering).
6. No impact on the API means that if this isn't enough it can be changed later without a major hassle for people.

**Comment by andrewplummer** [comment]
This has gone out in 2.0 so will close for now.
