### ISSUE TITLE
Different behavior of 1.4 String.assign and 2.0 String.format with Array

### ISSUE THREAD

**Issue by ermouth** [andrewplummer/Sugar#542]
For 1.4.1:
`"{0}{1}".assign(["first","second"])` >> `{0}first`

For 2.0:
`"{0}{1}".format(["first","second"])` >> `firstsecond`

Is it intentional?

**Comment by andrewplummer** [comment]
Yes! `format` is now 0-index. The fact that it was previously 1-index was a strange quirk that I justified by saying that regexes are also 1-index. However, this was confusing and now it is consistent with `format` from Python (as well as others). For more see #476

**Comment by ermouth** [comment]
Ok, thanks for explanation.
