### ISSUE TITLE
Expose which properties were set when a Date is created.

### ISSUE THREAD

**Issue by krisnye** [andrewplummer/Sugar#545]
I need to know if a date format that I'm parsing explicitly specified the time or not. This information appears to be available as the 'set' object within getExtendedDate. It would be nice for that information to be available after parsing a date.

The easiest way would be to simply assign the set object to your resulting date.set property. There are a few other ways to expose it, but this seems to have the smallest change to the API.

**Comment by krisnye** [comment]
If you are accepting pull requests, I can implement this.

**Comment by andrewplummer** [comment]
Definitely would like to avoid setting properties on native objects if it can be avoided. Also this especially doesn't make much sense as a property as it only represents the state at the time when the date was parsed, however the date's internal value can change after this.

One other possibility is to allow passing a `set` object in the `Date.create` method which will be used instead of an empty object and result in having the properties set on it instead.

**Comment by krisnye** [comment]
Yes, that is another probably better alternative. Wasn't sure if you were more protective of your current interface or the native objects. Either way, it would be very useful to me.

**Comment by andrewplummer** [comment]
Just added this as 8d64e70b147d319210451112a238f26740f66521.

**Comment by krisnye** [comment]
Cool, how do we use it?

**Comment by andrewplummer** [comment]
Oh yeah... most important part, huh? :)
Probably the most common (only?) use case would be something like this:
```
var set = {};
Date.create('thursday', { set: set });
```

`set` will then be populated with `{ weekday: 5 }`. Note that there may be other interim properties that aren't explicitly used when setting, for example one is "yearAsString" which is needed for year parsing etc.

**Comment by krisnye** [comment]
What are the potential values (not counting undocumented ones)? For my specific use case, I'm interested in whether or not a time component was specified.

These are the values I might expect:  {year,month,date,weekday,hour,minute,second}

I would check to see if time was set with:

    if (set.hour != null || set.minute != null || set.second != null)
        console.log('time was set')

**Comment by andrewplummer** [comment]
Yep, that's exactly it, including `milliseconds`.

**Comment by krisnye** [comment]
Excellent. Thanks again.

**Comment by krisnye** [comment]
@andrewplummer 
Does this still have the same API? I'm downloading the v2.04 version of the API and calling your sample does yield any values on the set.

    var set = {};
    Date.create('thursday', { set: set });
    console.log(JSON.stringify(set))
    // => {}

**Comment by andrewplummer** [comment]
Yes, this API has changed with version 2.0 ... it should now be `params` instead of `set`.

**Comment by krisnye** [comment]
Ok, thanks. Now I see where it is documented. Excellent.
