### ISSUE TITLE
Why "the end of this week" shows end of saturday instead of end of sunday?

### ISSUE THREAD

**Issue by adampietrasiak** [andrewplummer/Sugar#547]
Do I need to set last day of the week somehow? I think it might be sat in some countries

**Comment by andrewplummer** [comment]
Hey, sorry for the late reply. I was intending to respond to you by releasing 2.0, which includes the concept of "first day of the week" built into locales, but as always it's taking a more time than expected.

The summary is that the default locale is `en-US` in which the first day of the week is "Sunday", not "monday", but you will soon be able to control this. You will be able to simply use "the end of this week" in your language and it will correctly parse to the appropriate day of the week. Alternatively, you can call `endOfWeek` passing a locale code and don't need to worry about language.

For right now you can call `endOfISOWeek` which standardizes on Monday as being at the end of the week. This will continue to be available in 2.0. 

Thanks for your patience.

**Comment by andrewplummer** [comment]
This should be out now in 2.0.0!
