### ISSUE TITLE
Ordinal date creation for i18n doesn't work. Eg. for FR :  " Le 1er mai 2011"

### ISSUE THREAD

**Issue by alapiere** [andrewplummer/Sugar#548]
This test must pass but doesn't : 

`dateEqual(Date.create('Le 1er mai 2011'), new Date(2011, 4, 1), 'Date#create | basic French date');`
- Arnaud

**Comment by andrewplummer** [comment]
Is this basically "1st", "2nd", etc? If you can list out all of these I'll add the tests!

**Comment by alapiere** [comment]
**for FR (French) only** 

only ordinal rule is  :  **1 --> "1er"**

(french people don't use "2nd", "3rd" .. for day of week/month. )
Eg. 
09/01 /  september 1st -->  "1er septembre"
09/02 / september 2nd --> "2 septembre"
..

So only rule and test that must be implemented : 
dateEqual(Date.create('Le 1er mai 2011'), new Date(2011, 4, 1), 'Date#create | basic French date');

thanks :)

**Comment by andrewplummer** [comment]
Cool, easy fix then!

**Comment by vendethiel** [comment]
I can concur that's true.
