### ISSUE TITLE
Date.advance() does not work with parts-of-an-hour

### ISSUE THREAD

**Issue by Earl-Brown** [andrewplummer/Sugar#549]
Date.[advance,create]("2.25 hours") doesn't work.

Sure, I could Date.create().advance("2 hours").advance("15 minutes") - but that makes it REALLY difficult for a manually edited JSON configuration.

[Date.advance, Date.create]("2 hours from now") works just fine.  So I suspect any translation from relative that includes partials doesn't work correctly.

**Comment by andrewplummer** [comment]
OK you got it buddy.

This is going to be some kind of record... I'm literally deploying everything as we speak. Just managed to squeeze this through.

**Comment by Earl-Brown** [comment]
Awesome!  Thanks!

**Comment by andrewplummer** [comment]
What version are you using?

**Comment by vendethiel** [comment]
(hijacking this thread to say congrats :-).)

**Comment by andrewplummer** [comment]
Thanks man! It's going to be..................big....

**Comment by Earl-Brown** [comment]
I *think* I'm on 1.4.1

**Comment by andrewplummer** [comment]
Ok well in that case I may have to take everything back. It will go into 2.0.0 but I actually already deployed 1.5.0 just a few hours ago. 2.0.0 has a lot of breaking changes and on the assumption that it's non-trivial for you to upgrade, then this will have to be back-ported into 1.5.1.

It won't take long, but probably no records :)

**Comment by Earl-Brown** [comment]
OK...I appreciate it!

I look forward to using 2.0 - but I'm scared to jump into it right now and miss updating something.

**Comment by andrewplummer** [comment]
Yeah, that's fair. Maybe you'd like to test out the new upgrade script. Kinda need someone to beta test it. The link is here:

https://sugarjs.com/upgrading

It'll be live..........soon....

**Comment by Earl-Brown** [comment]
I'll give it a go.  Doing backups now :)

**Comment by andrewplummer** [comment]
Aaaaaaand it's live!

**Comment by Earl-Brown** [comment]
Cool...

Looks like the change for "advance()" didn't make it into the docs, tho...testing it on the docs page shows current time instead of advanced time.

But the upgrade to 2.0 wasn't that painful at all...so far..I hope I haven't missed anything!  

And .advance() is working for me there.

**Comment by vendethiel** [comment]
\o/ 2013 me believed in it all along :-). Amazing!

**Comment by andrewplummer** [comment]
@Earl-Brown Forgot to push the build!  Advance should work on the docs page now, but might have to clear some caches.

**Comment by andrewplummer** [comment]
@vendethiel My god 2013.... unbelievable... :D

**Comment by vendethiel** [comment]
Oh, yeah, I have all sorts of way of making me feel old.
I was in high school back then.

**Comment by Earl-Brown** [comment]
@vendethiel ... how cute.  My *kids* were in high school back then :)

**Comment by andrewplummer** [comment]
@Earl-Brown THANK YOU :D

**Comment by Earl-Brown** [comment]
Oh, no - thank YOU!!!

I love this library.  One of the most useful I've come across.

**Comment by Earl-Brown** [comment]
How can I give more immediate feedback on issues as they come up?  I'd rather not clutter the "issues" list with something *just* rolled out...

**Comment by andrewplummer** [comment]
Closing this for now. Feel free to raise new issues!
