### ISSUE TITLE
In release 2.0, "".pluralize() is not a function

### ISSUE THREAD

**Issue by Earl-Brown** [andrewplummer/Sugar#550]
Date.create() works, but "".pluralize() yields a TypeError (at least in Chrome)

I have made sure that Sugar.extend() is called.

What tips do you have for resolving this?

**Comment by andrewplummer** [comment]
So, first, are you using the main builds? Pluralize isn't part of the default build (actually it never was). There are a few ways you can build it, the easiest is through the site's new "custom build" too. If you're using it in node you may have to hold tight until the `sugar-inflections` package is pushed.. should be soon though....

**Comment by Earl-Brown** [comment]
Using it in Chrome.  I downloaded the "Sugar.js" from the main page.

I'll try from the builder

**Comment by andrewplummer** [comment]
How were you using it before?

**Comment by Earl-Brown** [comment]
I'm not *sure*, but I think that's how I got it before.  It's been a while :)

**Comment by andrewplummer** [comment]
But was it always through the site?

**Comment by Earl-Brown** [comment]
Yep.

**Comment by andrewplummer** [comment]
Hmm that's strange then.. The inflections module was always excluded from the default build...

**Comment by Earl-Brown** [comment]
I might have gotten it from the old builder...I really don't remember

**Comment by andrewplummer** [comment]
I'm just happy someone's using it! It was always kinda off the map... was wondering if it was all that useful....

**Comment by Earl-Brown** [comment]
I figured "if someone else wrote it, it saves me trouble" :)

**Comment by Earl-Brown** [comment]
Fun fact: I'm using the same .JS file for Node and UI ... yesterday the pre-upgrade version was cached.  Today it loaded the new one.  And doesn't like it much :)  I didn't fix any of my Node code.

**Comment by andrewplummer** [comment]
Hmm... so to answer your question from yesterday I'm not really sure the best forum to help you out with this... if nothing comes to mind you could always shoot me an email...

**Comment by Earl-Brown** [comment]
Do you have a chat client that you use?  Or would email be better?

**Comment by andrewplummer** [comment]
Email is maybe better for now I guess

**Comment by Earl-Brown** [comment]
Using the full build fixed the issue.
