### ISSUE TITLE
SortOrder issue

### ISSUE THREAD

**Issue by Mottie** [andrewplummer/Sugar#556]
It appears that a similar problem to #382 has popped up in Sugar v2.0.0.

I set up [this demo](https://jsfiddle.net/Mottie/yh3pyvxL/) using the default and Icelandic sort orders

Default
```
AÁÀÂÃĄBCĆČÇDĎÐEÉÈĚÊËĘFGĞHıIÍÌİÎÏJKLŁMNŃŇÑOÓÒÔPQRŘSŚŠŞTŤUÚÙŮÛÜVWXYÝZŹŻŽÞÆŒØÕÅÄÖ
sorts to
AÄÂÃÁÀĄBCÇĆČDĎÐEÈËÉÊĚĘFGĞHıIÍÎÏÌİJKLŁMNŃŇÑOÒÔÖÕÓPQRŘSŚŠŞTŤUÚÜÙÛŮVWXYÝZŹŻŽÞÆŒØÅ
```

Icelandic
```
AaÁáBbCcDdÐðEeÉéĘęFfGgHhIiÍíJjKkLlMmNnOoÓóPpQqRrSsTtUuÚúVvWwXxYyÝýZzÞþÆæÖö
sorts to
AaáÁBbcCDdÐðEeéÉĘęfFgGhHiIÍíjJkKLlMmNnOoÓóÖöPpQqRrsSTtuUÚúVvwWXxyYÝýZzÞþÆæ
```

**Comment by Mottie** [comment]
Nevermind! I wasn't setting the options using `Sugar.Array.setOption`.

Thanks for all your work!

**Comment by Mottie** [comment]
Ugh, sorry... actually it appears that using `Sugar.Array.sortCollate` ignores the options: see [updated demo](https://jsfiddle.net/Mottie/yh3pyvxL/)

Default
```
Before:
AÁÀÂÃĄBCĆČÇDĎÐEÉÈĚÊËĘFGĞHıIÍÌİÎÏJKLŁMNŃŇÑOÓÒÔPQRŘSŚŠŞTŤUÚÙŮÛÜVWXYÝZŹŻŽÞÆŒØÕÅÄÖ

After:
ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞĄĆČĎĘĚĞİıŁŃŇŒŘŚŞŠŤŮŹŻŽ
```

Icelandic
```
Before:
AaÁáBbCcDdÐðEeÉéĘęFfGgHhIiÍíJjKkLlMmNnOoÓóPpQqRrSsTtUuÚúVvWwXxYyÝýZzÞþÆæÖö

After:
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÁÆÉÍÐÓÖÚÝÞáæéíðóöúýþĘę
```

**Comment by andrewplummer** [comment]
It looks like you're using `Sugar.Array.sortCollate`, however that has also moved behind `getOption`, so this should instead be `.sort(Sugar.Array.getOption('sortCollate'))`.

As for the docs, sorting options are listed [here](https://sugarjs.com/docs/#/ArraySorting) instead of in the main API method search.

**Comment by Mottie** [comment]
Thank you for clearing things up!

**Comment by andrewplummer** [comment]
No problem!
