### ISSUE TITLE
Feature request: Number#fround(precision)

### ISSUE THREAD

**Issue by Slayer95** [andrewplummer/Sugar#560]
In analogy to `Number#round()`.

**Comment by andrewplummer** [comment]
While `Number#round` allows you to control the precision, this doesn't seem to require that, so it could just be mapped as an alias similar to `pow`, `abs`, etc. Would this satisfy your needs?

**Comment by Slayer95** [comment]
The idea is for ``Number#fround`` to <em>do allow</em> to control precision, in the same way as ``Number#round`` does.

Note that neither ``Math.round`` nor ``Math.fround`` themselves have a precision parameter built-in.

I'm currently shimming it like so, btw: [https://github.com/Slayer95/Pandora-Showdown/blob/8fe91896fdd4a4927fbde6ffdc098945254ca651/tools.js#L47-L65](Number#fround)

**Comment by andrewplummer** [comment]
So, after playing around with your example a bit, I'm still having trouble understanding the meaning (or at least the utility) of having a "places" argument. `round` is clear as this is natural language. Although according to the spec it rounds to the nearest integer, it is not a stretch for a parameter to allow rounding to a specific place. `fround`, however is not natural language, the method specifically rounds to single-precision, and the `places` argument isn't immediately clear what it's indicating.

Anyway, let's set all this feedback aside. In either case, this idea is a perfect candidate for using the new plugin system of v2.0. I just recently created a boilerplate repo [here](https://github.com/andrewplummer/sugar-plugin-boilerplate). There are a lot of notes and it should be easy to follow along.

**Comment by andrewplummer** [comment]
Going to close this for now. Let me know if there are issues with the plugin mechanism, etc.
