### ISSUE TITLE
Where did pluralize go to?

### ISSUE THREAD

**Issue by graham-sportsmgmt** [andrewplummer/Sugar#564]
I'm using sugar 2.02 in node.js 6.9 (ES6), and need the pluralize method.  However, these are the only fields to the Sugar.String object that are available to me.  The others that seem to be missing are endsWith, hankaku, hasScript, hiragana, humanize, isScript, katakana, repeat, singularize, startsWith, trim, zenkaku, addAcronym, addHuman, and addPlural.

> at
> camelize
> capitalize
> chars
> codes
> compact
> dasherize
> decodeBase64
> encodeBase64
> escapeHTML
> escapeURL
> first
> forEach
> format
> from
> includes
> insert
> isBlank
> isEmpty
> last
> lines
> pad
> padLeft
> padRight
> parameterize
> remove
> removeAll
> removeTags
> replaceAll
> reverse
> shift
> spacify
> stripTags
> titleize
> to
> toNumber
> trimLeft
> trimRight
> truncate
> truncateOnWord
> underscore
> unescapeHTML
> unescapeURL
> words
> range

**Comment by andrewplummer** [comment]
Hi, I'm assuming you're using npm to install?
As of 2.0.0 these methods are now part of the `sugar-inflections` and `sugar-language` packages. They were never included in the default build of Sugar outside npm, so the package was updated to separate them out. Just install those 2 packages and you should be good to go.

**Comment by graham-sportsmgmt** [comment]
Thanks, Andrew.  I was able to add those then access them through adding a require('sugar-inflections');

Is there an easy way to merge this into the main Sugar object?

Also, can I help you with the docs to update them to reflect these changes?

**Comment by graham-sportsmgmt** [comment]
Excellent, this is working perfectly for me now.  Thank you again.

It would be helpful to show that example above in the docs, and also to flag functions that live in the inflections or language modules.

**Comment by andrewplummer** [comment]
> It would be helpful to show that example above in the docs

Good point! I made a note of it.

> and also to flag functions that live in the inflections or language modules.

Have a look [here](https://sugarjs.com/docs/#/String/pluralize). Hover over the module icon on the top right next to the close button. Maybe this needs to be more prominent?

**Comment by graham-sportsmgmt** [comment]
I would like it to be more prominent, I'd suggest that it would be best as a full word "Inflections" formatted just like the "Instance" box next to it (with a different color) and the tooltip text says "Included in add-on Inflections library".  That makes it very clear to someone getting started with Sugar that this function is NOT in the default String collection.

**Comment by andrewplummer** [comment]
ok good point... also noted!

**Comment by andrewplummer** [comment]
Ok, I'm not ready to part with the design quite yet, but what I have done is changed the wording:

Default: "Included in the Array module. This module is part of the default build and main npm package."

Non-default: "Included in the Inflections module. This add-on module can be included in the download page or found in the "sugar-inflections" npm package."

Also updated the getting started page to include an example of using 2 different npm packages in tandem.

Thanks for your help here!

**Comment by graham-sportsmgmt** [comment]
Thank you for creating SugarJS, and being so responsive!
