### ISSUE TITLE
"Sugar is not defined" in browser

### ISSUE THREAD

**Issue by Earl-Brown** [andrewplummer/Sugar#565]
Sugar.js runs in my web page, but when I attempt to reference Sugar, I get "Sugar is not defined".

I have stepped through the debugger to see that Sugar is loading before I attempt to reference it.

I can see that the code is Node-friendly; is there a missing assignment to "global.Sugar = ..."?

**Comment by andrewplummer** [comment]
Do you have any more details? Which version of Sugar? Which exact environment? Where did you get the build, etc?

**Comment by Earl-Brown** [comment]
It's an electron application.  I downloaded the latest from the downloads page.  Version 2.02.

I'll try the same UI in Chrome and see if it misbehaves in the same way.  If it does, I'll get you the code.

**Comment by Earl-Brown** [comment]
Quite an interesting thing - when I run it in Chrome (straight off the file system), it works great.  So there's something wrong with using Sugar in an Electron application ...

**Comment by andrewplummer** [comment]
So, I'm not very familiar with Electron, but I just did the sample project off the main page, used `npm install sugar`, and then this:

```
const Sugar = require('sugar');
```

and it works fine for me. I'm probably missing something about what you're trying to do or how you're trying to load Sugar?

**Comment by andrewplummer** [comment]
Ah ok I see what you mean now. It seems to be because Electron is injecting a node environment into the browser environment. This means that the detection between the two can no longer be made. There might be a solution here: http://electron.atom.io/docs/faq/#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron

**Comment by Earl-Brown** [comment]
I stepped through with "break on all exceptions" set, and I'm getting one on line 806: "Caller" and "arguments" are restricted function properties and cannot be accessed in this context

This exception happens twice - once for "arguments" and then for "caller".  Here is the call stack:
mapNativeToChainable
createNamespace
(anonymous)
forEachProperty
setupGlobal

**Comment by andrewplummer** [comment]
Is that with or without the "nodeIntegrationFalse" flag? I turned that on, and it's working for me...

**Comment by Earl-Brown** [comment]
Ah ... I see (hadn't noticed your response when I posted my last)...

So, sugar is detecting "require" and trying to use it?  And since it's the "wrong" require, it doesn't work right?

**Comment by andrewplummer** [comment]
Well, the thing is even without the flag, I don't get the exceptions you listed above. But in any case the problem is with this:

```
// Is the environment node?
var hasExports = typeof module !== 'undefined' && module.exports;
```

require isn't checked, but module and module.exports is, which are both defined. I don't see how you could use most libs that work with both node and browser with this setup because there would be no way to make a distinction between them. However, if you're willing to hack a bit, then just change the `hasExports` variable to `false`, and I would think it should work!

**Comment by andrewplummer** [comment]
As for the exceptions you mentioned, this kind of access error *does* happen (there's even a note about it just below line 806), which is why they're in a try/catch block... so if that's the case it shouldn't be throwing? But again, I don't get those errors in the first place.

**Comment by Earl-Brown** [comment]
I only caught those exceptions by telling the debugger to break on *every* exception - even caught exceptions.

**Comment by Earl-Brown** [comment]
Thanks for your help - I fixed it.  This little snippet at the top of my page worked:

```html
<script type="text/javascript">
const _require = window.require,
	_exports = window.exports,
	_module = window.module;

delete window.require;
delete window.exports;
delete window.module;

</script>
```

Now I get the best of both worlds.

**Comment by andrewplummer** [comment]
Ok that sounds like a pretty good solution. I'm surprised they don't do that anyway, I can't imagine what other havoc that could wreak.

**Comment by Earl-Brown** [comment]
Yeah - if I end up using electron enough, I will probably suggest it.  

If it hasn't already been suggested.

**Comment by Earl-Brown** [comment]
... in fact, I like this option better - it seems to be much more the way electron should  have done things:

```html
		<script type="text/javascript">
			var electron = electron || {};
			electron.require = window.require;
			electron.exports = window.exports;
			electron.module = window.module;

			delete window.require;
			delete window.exports;
			delete window.module;
		</script>
```

**Comment by andrewplummer** [comment]
Yeah, I would prefer that too I think.
