### ISSUE TITLE
How do I import this thing? (TypeScript ES6/ES2015 + Webpack)

### ISSUE THREAD

**Issue by qvazzler** [andrewplummer/Sugar#566]
So far the below seems to work in terms of assigning Sugar to the global scope.

```
require("expose-loader?Sugar!sugar");
```

Testing it in the web browser shows that it is working.
However I am having zero luck being able to use the now bundled definitions file!

I do not want use the old /// method, it is deprecated as of latest typescript versions.

Any advice for me? Thanks!

**Comment by qvazzler** [comment]
Also the below:

```
import * as Sugar from "sugar";
```

Leads to

> "File '.../node_modules/sugar/sugar.d.ts' is not a module

**Comment by andrewplummer** [comment]
This isn't a exactly a duplicate, but can we move this over to #529? The typescript definitions just went out, and they likely need some help here. I didn't know, for instance, that the /// method was deprecated -- we've been proceeding on that thread with that as the assumption. Maybe you can provide some insight here?
