### ISSUE TITLE
UTC time

### ISSUE THREAD

**Issue by IsaacAbrahamson** [andrewplummer/Sugar#567]
I am working on a simple API, and I cannot get UTC time to work correctly.
```javascript
var date = "today";
const utc = Date.create(date, { fromUTC: true }); // 2016-11-27T00:00:00.000Z
const timestampUnix = utc.format('{X}'); // 1480204800 (today)
```
and I get
```
{
  "input": today,
  "utcTimestamp": "1480204800"
}
```
which is correct. Now, I know what the utc timestamp for today is, but when I try this:
```javascript
var date = 1480204800;
const utc = Date.create(date, { fromUTC: true }); // 1970-01-18T03:10:04.800Z
const timestampUnix = utc.format('{X}'); // 1480204
```
```
{
  "input": 1480204800,
  "utcTimestamp": "1480204"
}
```
And when I create a date with a UTC timestamp (which I got before), I do not get the right date? Am I using the library wrong, or what, I am confused.

**Comment by andrewplummer** [comment]
First, I've just released some [new documentation](https://sugarjs.com/dates/#/UTCTime) that might help you here, in case you haven't seen it.

One of the first things I'm noticing is that you're using a Unix timestamp for output (`{X}` which is in seconds), but Javascript accepts input in milliseconds. That might be a good place to start?

**Comment by andrewplummer** [comment]
I just updated the site to make it more clear that `{X}` is seconds and `{x}` is milliseconds.

**Comment by IsaacAbrahamson** [comment]
Thank you, I am looking at the documentation again, I will see if I can get it workinng and the re-comment.

**Comment by IsaacAbrahamson** [comment]
> Javascript accepts input in milliseconds.

Is there any way to set it to accept input in seconds?

**Comment by andrewplummer** [comment]
Sure... `seconds * 1000` :)

Javascript is all in milliseconds. That's its standard.

**Comment by IsaacAbrahamson** [comment]
> Sure... seconds * 1000 :)
> Javascript is all in milliseconds. That's its standard.

I don't think you understand what I meant. For example if I do this:
```
Date.create(1480377600000) // input in milliseconds - date is correct
Date.create(1480377600) // input in seconds - is not correct
```
And I am getting the date with a parameter, so I cannot just times it by 1000...
```
Date.create(1480377600000 * 1000) // gives wrong date
Date.create(1480377600 * 1000) // gives correct date
```
I cannot just times it by 1000, because I cannot guarantee if the timestamp will be in seconds or milliseconds, because I get it from the user. Is there someway that I can do a check or something like this?
```
Date.create(1480377600000) // today
Date.create(1480377600) // today
```

I can possibly check myself for length of string and then multiply based on that, but I wondered if your library had something built in like that. Sorry if I am confusing, I hope you see what I am trying to do.

**Comment by andrewplummer** [comment]
Ah, I see what you mean now. You yourself don't know if it's in seconds or milliseconds. Ultimately, however, the input is ambiguous, as `1480377600` is also a valid value in milliseconds, so it falls to your application side logic to "disambiguate" the input before it is passed in. The best way is likely to force the user to choose whether the input is seconds or milliseconds. However if you're willing to accept an 80% solution, here's one idea:

If we are to take the value in milliseconds of `2524575600000`, which is the year 2050, and divide by 1000, the result would be January 30, 1970. This essentially means that you could take any values less than `2524575600` and multiply by 1000. This would result in values in seconds being "correctly" interpreted up to the year 2050, while only being incorrect when the input is in the range of January 1 - January 30, 1970. I probably would not take an approach like this myself, however depending on the requirements of your app, this potential for error may be acceptable.
