### ISSUE TITLE
A couple of typos in documentation

### ISSUE THREAD

**Issue by gamtiq** [andrewplummer/Sugar#570]
There are the following typos in documentation comments.
In the comment for [`Array.isEqual`](https://github.com/andrewplummer/Sugar/blob/2.0.2/lib/array.js#L462):
> Objects in the array are considered equal if they are not *obserably* distinguishable.

In comments for [`Array.getOption`](https://github.com/andrewplummer/Sugar/blob/2.0.2/lib/array.js#L30) and [`Array.setOption`](https://github.com/andrewplummer/Sugar/blob/2.0.2/lib/array.js#L43):
> an option used *interally* by Array.

**Comment by andrewplummer** [comment]
Thank you! Just deployed a fix for this now. Should be good.
