### ISSUE TITLE
Clarify meaning of observably distinguishable

### ISSUE THREAD

**Issue by cowwoc** [andrewplummer/Sugar#575]
The best definition I could find for observably distinguishable is on `Object.isEqual()`:

> If both objects are built-in types, they will be considered equivalent if they are not "observably distinguishable". This means that primitives and object types, 0 and -0, and sparse and dense arrays are all not equal. [...]

Could you please clarify the second part of the sentence? What do you mean that all those types are not equal? They're not equal to anything?! :)

Do you mean that each type can be compared to itself, but a primitive number is not equal to an object Number, even if they represent the same value? Similarly, sparse and dense arrays with the same values are not evaluated as equal. Is that what you meant?

**Comment by andrewplummer** [comment]
Yeah, this could be worded better. It means that sparse and dense arrays that are otherwise equivalent aren't treated as equal as a difference can be "observed" (in this case `n in array` would return true for a dense array and false for a sparse one. Likewise a `typeof` operator would distinguish a primitive from object Number.

Will revisit the wording of this one. Any suggestions?

**Comment by cowwoc** [comment]
What you just said sounds perfect to me. Alternatively, how about this?

> If both objects are built-in types, they will be considered equivalent if they are not "observably distinguishable". Meaning, values that are otherwise equivalent (primitive and object representations of a value, 0 and -0, sparse and dense arrays) will return false.

**Comment by andrewplummer** [comment]
Went with basically what you wrote:

> Returns `true` if `obj` is equivalent to the object.
>
> If both objects are built-in types, they will be considered
> equivalent if they are not "observably distinguishable". This means
> that objects that can otherwise be considered equivalent (primitives
> and their object counterparts, `0` and `-0`, sparse and dense arrays)
> will return `false`. Functions and non-built-ins like instances of
> user-defined classes and host objects like Element and Event are
> strictly compared with `===`, and will only be equivalent if they
> are the same reference. Plain objects as well as Arrays will be
> traversed into and deeply checked by their non-inherited, enumerable
> properties. Other allowed types include Typed Arrays, Sets, Maps,
> Arguments, Dates, Regexes, and Errors.

**Comment by cowwoc** [comment]
Thank you. Closing the issue.

**Comment by andrewplummer** [comment]
Ok. Docs will go out with the next version.
