### ISSUE TITLE
Extract date format of input

### ISSUE THREAD

**Issue by alexemorris** [andrewplummer/Sugar#578]
I love this library, is there any way of detecting the input date format? For example if I have a string 23/03/2016 12:03:44 then I can use sugar to automatically infer that the date format is "yyyy/MM/dd HH:mm:ss" ?

**Comment by andrewplummer** [comment]
Well, don't you mean `dd/MM/yyyy`? In any case, yes! Passing `params` as an option to [create](https://sugarjs.com/docs/#/Date/create) will populate that object:

```javascript
var params = {};
Sugar.Date.create(str, { params: params });
```

If, however, your question is about `dd/MM` vs. `MM/dd`, then you basically need to pass a different locale code, as that format is inherently ambiguous. `en` and `en-US` will (with apologies to Europeans) be inferred as `MM/dd`, anything else will be `dd/MM`.
