### ISSUE TITLE
Extended behaviour for chainables

### ISSUE THREAD

**Issue by springfirenator** [andrewplummer/Sugar#586]
Hello, is it possible to removing .raw property and just arrive at the result just like extended objects?

```
Sugar.Date('today').addDays(2).format('{mm}'); //should return string
Sugar.Date().addDays(6); //should return date
Sugar.Number(56).format(); //should return string
```

**Comment by andrewplummer** [comment]
You're looking for the static forms:

’’’
Sugar.Date.addDays(new Date, 6);
Sugar.Number.format(56);
// Etc..
’’’

**Comment by andrewplummer** [comment]
Going to close this for now. Let me know if there's anything more!
