### ISSUE TITLE
TypeError: Unmatched } in format string

### ISSUE THREAD

**Issue by XadillaX** [andrewplummer/Sugar#587]
It's OK while I'm using 1.4 but broken under 2.

```javascript
("{ name: '{name}' }").assign/format({ name: "Hi" });
```

**Comment by andrewplummer** [comment]
Hi... according to the docs "Literal braces in the string can be escaped by repeating them.". This hasn't changed since 1.4, so if this was ever working before it was definitely a bug. It seems that you're intending the outer braces to be unescaped so you should instead be using:

```javascript
("{{ name: '{name}' }}").assign/format({ name: "Hi" });
```

**Comment by andrewplummer** [comment]
To be clear, without escaping you are nesting 2 meaningful braces, which isn't allowed, which explains the error message you're seeing.

**Comment by andrewplummer** [comment]
Going to close this one for now.
