### ISSUE TITLE
Unextend

### ISSUE THREAD

**Issue by florianGithub** [andrewplummer/Sugar#588]
I cannot switch back to the default mode after calling "Sugar.extend();"
Even after reloading the page without cache.

**Comment by andrewplummer** [comment]
Sugar doesn't hold anything in local storage, cookies, or anything else (it's not even aware of the browser window effectively). Maybe you're unintentionally calling `.extend` somewhere you're not aware?

**Comment by andrewplummer** [comment]
Will close this for now... please let me know if there is still an issue.
