### ISSUE TITLE
Indonesian Locale Or Example English Locale File

### ISSUE THREAD

**Issue by l1nknyto** [andrewplummer/Sugar#602]
Hi,

I need indonesian locale, but it seems it not exists yet.
So i want to create and contribute it. It will easier if i create from english locales.
I have search for existing english locale, but no luck for finding it.
Could you give me source of english locales?

Thanks

**Comment by andrewplummer** [comment]
Thank you for your contribution!

Please use the format in the other locale files (in `lib/locales`) and use the filename `id.js` (this code should be appropriate). The English definition is at the bottom of the `lib/date.js` file.

Let me know if you have questions!

**Comment by l1nknyto** [comment]
Thanks

Ok, i'm finish it (fork, and add id.js)
I see that you make a test for each locale.
I think i will be difficult to create test file (because i haven't done it yet)
and i try to run 'gulp test', but an error occured
` Failure: 
 Since/Until | Relative dates should not be influenced by other input 
 Expected: 7 but was: 6 
 File:  Object.fn (/tmp/Sugar/test/tests/date.js, Line: 2595`

Anyway if i use id.js in my project its working well as i expected (currently i'm using for relative method)
Thanks for you help

Should i merge to yours?

**Comment by andrewplummer** [comment]
Please create a pull request, and I'll have a look at the tests. Thanks!

**Comment by andrewplummer** [comment]
Hi ... sorry for taking ages on this ... are you still interested in contributing?

**Comment by l1nknyto** [comment]
Hi, Andrew

I lost my patch files and also already delete the fork.
Sorry, i can't contribute now, kinda busy. may be in another time.

Thanks a lot for your help before.

**Comment by andrewplummer** [comment]
Ah that's too bad ... may have missed my chance. If you have time and feel like contributing let me know!

In the meantime I also have a survey that would be amazing if you could help with... it should only take 5-10 minutes...

**Comment by andrewplummer** [comment]
Link here: https://docs.google.com/spreadsheets/d/1NnSf_gNGvsM7UbTojChOgNphNa5F7oMkOhx7tToiMbU/edit?usp=sharing

**Comment by l1nknyto** [comment]
done answer survey

**Comment by andrewplummer** [comment]
Awesome! Thank you!

**Comment by andrewplummer** [comment]
Ok will close this one for now then... please feel free to open again if you would like to contribute! Thank you!
