### ISSUE TITLE
Date formating in "ru" locale.

### ISSUE THREAD

**Issue by Costegillio** [andrewplummer/Sugar#622]
Greetings!

I have:
Sugar.Date.format(new Date(), "{month}", "ru") > декабря

How can i get "декабрь" instead of "декабря", "сентябрь" instead of "сентября" and etc?

**Comment by andrewplummer** [comment]
Hi,

variants can be specified with numbers in the formatting tokens. In this case, `{month4}` will return what you want. Since all languages are different, there's not an overall applicable rule to the different types of tokens... it's easiest just to try them out for yourself.

**Comment by Costegillio** [comment]
Thanks, Andrew, your project is awesome.

**Comment by andrewplummer** [comment]
Hello... I'm considering a better system for Sugar's formatting tokens and I need your help! Could you please fill out [this sheet](https://docs.google.com/spreadsheets/d/1NnSf_gNGvsM7UbTojChOgNphNa5F7oMkOhx7tToiMbU/edit?usp=sharing) for Russian? If you have any questions let me know! Thank you in advance!

**Comment by Costegillio** [comment]
Greetings!

Done.

**Comment by andrewplummer** [comment]
Awesome! Thank you!
