### ISSUE TITLE
Array Docs - example for find uses assignment operator, not comparison operator

### ISSUE THREAD

**Issue by graham-sportsmgmt** [andrewplummer/Sugar#633]
The [docs for Array.find](https://sugarjs.com/docs/#/Array/find) use the wrong operator in the example.

Current:

```
users.find(function(user) {
  return user.name = 'Harry';
});
```

Should be:

```
users.find(function(user) {
  return user.name == 'Harry';
});
```

**Comment by andrewplummer** [comment]
Good catch! Thanks will fix.

**Comment by graham-sportsmgmt** [comment]
We're using sugarjs extensively and loving it, please let me know if there's something I can do to help with this project.

**Comment by andrewplummer** [comment]
Happy to hear it! Will let you know!

**Comment by andrewplummer** [comment]
Updated! Thanks!
