### ISSUE TITLE
Unable to use sugar-date on server-side with meteor/nodejs

### ISSUE THREAD

**Issue by WayneUong** [andrewplummer/Sugar#640]
```
var Sugar = require('sugar-date');
console.log(Sugar.Date())
```
gives me `TypeError: Sugar.Date is not a function`

**Comment by andrewplummer** [comment]
Hi sorry for the delay... were you able to figure this one out? I have no trouble installing `sugar-date` and using it like this out of the box... it's unlikely that meteor could be messing with basic import/exports so maybe something else was missing here?

**Comment by andrewplummer** [comment]
Going to close this one out as I wasn't able to reproduce it, even after using in conjunction with Meteor... seems like something else must be at play here. If you still are having trouble please feel fre to reopen but if you can provide some more context it would be helpful.
